=== gbevin/rife/rife_v1_remaining/shared/dtd/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: config.dtd 3918 2008-04-14 17:35:35Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Config 1.0//EN
  -  SYSTEM ID: http://rifers.org/dtd/config_1_0.dtd
  -->

<!ELEMENT config	(param|list|include)*>

<!ELEMENT param     (#PCDATA|value|property)*>
<!ATTLIST param	    name CDATA #REQUIRED
					final (0|f|false|1|t|true) "false">

<!ELEMENT value     EMPTY>
<!ATTLIST value     name CDATA #REQUIRED>

<!ELEMENT list      (item*)>
<!ATTLIST list      name CDATA #REQUIRED
					final (0|f|false|1|t|true) "false">

<!ELEMENT item      (#PCDATA|value|property)*>

<!ELEMENT include	EMPTY>
<!ATTLIST include   file CDATA #REQUIRED>

<!ELEMENT property  EMPTY>
<!ATTLIST property  name CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/rep/config-common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: config-common.xml 3943 2008-04-27 09:09:02Z gbevin $
  -->

<!DOCTYPE config SYSTEM "/dtd/config.dtd">

<config>
	<param name="IOC_CONFIG">IOC_DATABASE</param>
	<param name="IOC_DATABASE">pgsql</param>
	<param name="DATASOURCE_USER">unittests</param>
	<param name="DATASOURCE_PASSWORD">password</param>

	<param name="TEMPLATE_AUTO_RELOAD">true</param>
	<param name="TEMPLATE_DEFAULT_ENCODING">ISO-8859-1</param>
	<param name="TEMPLATE_CONFIG_VALUE">the config value</param>
	<param name="AUTO_RELOAD_DELAY">0</param>

	<param name="SITE_AUTO_RELOAD">true</param>
	<param name="ELEMENT_AUTO_RELOAD">true</param>

	<param name="FILEUPLOAD_SIZE_LIMIT">4096</param> <!-- 4KB -->
	<param name="FILEUPLOAD_SIZE_CHECK">true</param>

	<param name="GZIP_COMPRESSION">true</param>

	<param name="SQL_DEBUG_TRACE">false</param>
	<param name="ELEMENT_DEBUG_TRACE">false</param>

	<param name="TRANSACTION_TIMEOUT">20</param>

	<param name="L10N_DEFAULT_LANGUAGE">en</param>
	<param name="L10N_DEFAULT_COUNTRY">BE</param>
	<param name="L10N_DEFAULT_TIMEZONE">CET</param>

	<param name="PRETTY_ENGINE_EXCEPTIONS">false</param>

	<param name="ENGINE_ELEMENT_CONFIG_VALUE">the element config value</param>
	<param name="EXPRESSION_CONFIG_VALUE_BOOL">true</param>
	<param name="EXPRESSION_CONFIG_VALUE">the value</param>

	<param name="scheduler_value">value2</param>

	<!-- Supported config values -->
	<!--

	Config:
	CONFIG_PREFERENCES_USER
	CONFIG_PREFERENCES_SYSTEM

	Global:
	TEMP_PATH
	APPLICATION_CLASSPATH
	JAVA_COMPILER_PATH
	JAVA_COMPILER_ARGS
	JAVA_COMPILER_INTERNAL
	USE_FAST_EXCEPTIONS

	Authentication:
	SESSION_DURATION
	SESSION_PURGE_FREQUENCY
	SESSION_PURGE_SCALE
	SESSION_RESTRICT_HOSTIP
	REMEMBER_DURATION
	REMEMBER_PURGE_FREQUENCY
	REMEMBER_PURGE_SCALE
	TABLE_ROLE
	SEQUENCE_ROLE
	TABLE_USER
	TABLE_ROLELINK
	TABLE_AUTHENTICATION
	TABLE_REMEMBER
	ROLE_NAME_MAXIMUM_LENGTH
	LOGIN_NAME_MAXIMUM_LENGTH
	LOGIN_NAME_MINIMUM_LENGTH
	PASSWORD_MAXIMUM_LENGTH
	PASSWORD_MINIMUM_LENGTH

	Cmf:
	SEQUENCE_CONTENTREPOSITORY
	SEQUENCE_CONTENTINFO
	TABLE_CONTENTREPOSITORY
	TABLE_CONTENTINFO
	TABLE_CONTENTATTRIBUTE
	TABLE_CONTENTPROPERTY
	TABLE_CONTENTSTOREIMAGE
	TABLE_CONTENTSTORETEXT
	TABLE_CONTENTSTORERAWINFO
	TABLE_CONTENTSTORERAWCHUNK

	Database:
	TRANSACTION_TIMEOUT
	SQL_DEBUG_TRACE

	Engine:
	AUTO_RELOAD_DELAY
	DEFAULT_CONTENT_TYPE
	ELEMENT_AUTO_RELOAD
	ELEMENT_GENERATION_PATH
	ELEMENT_DEBUG_TRACE
	ELEMENT_DEBUG_MEMORY
	LOG_ENGINE_EXCEPTIONS
	PRETTY_ENGINE_EXCEPTIONS
	FILEUPLOAD_PATH
	FILEUPLOAD_SIZE_LIMIT
	FILEUPLOAD_SIZE_CHECK
	FILEUPLOAD_SIZE_EXCEPTION
	SITE_AUTO_RELOAD
	CONTINUATION_DURATION
	CONTINUATION_PURGE_FREQUENCY
	CONTINUATION_PURGE_SCALE
	GZIP_COMPRESSION
	GZIP_COMPRESSION_TYPES
	LOCAL_FORWARD_PORT
	PROXY_ROOTURL
	WEBAPP_CONTEXT_PATH
	RESPONSE_REQUIRES_SITE
	SITE_INITIALIZING_REDIRECT_URL
	SITE_INITIALIZING_PASSTHROUGH_SUFFIXES
	REQUEST_ENCODING
	RESPONSE_ENCODING
	SESSION_STATE_STORE_CLONING
	
	Resources:
	TABLE_RESOURCES

	Scheduler:
	TABLE_TASK
	SEQUENCE_TASK
	TABLE_TASKOPTION
	TASKOPTION_NAME_MAXIMUM_LENGTH
	TASKOPTION_VALUE_MAXIMUM_LENGTH
	TASK_TYPE_MAXIMUM_LENGTH
	TASK_FREQUENCY_MAXIMUM_LENGTH

	Swing:
	ICON_CONFIRM_PATH
	ICON_ERROR_PATH
	ICON_INFO_PATH

	Template:
	TEMPLATE_AUTO_RELOAD
	TEMPLATE_DEFAULT_ENCODING
	TEMPLATE_GENERATION_PATH
	TEMPLATE_GENERATE_CLASSES
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_ENGINEHTML
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_ENGINEXHTML
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_ENGINEXML
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_ENGINETXT
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_HTML
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_XHTML
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_XML
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_TXT
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_SQL
	TEMPLATE_DEFAULT_RESOURCEBUNDLES_JAVA

	Tools:
	L10N_RESOURCEBUNDLE_AUTO_RELOAD
	L10N_DEFAULT_RESOURCEBUNDLE
	L10N_DEFAULT_LANGUAGE
	L10N_DEFAULT_COUNTRY
	L10N_DEFAULT_SHORT_DATEFORMAT
	L10N_DEFAULT_LONG_DATEFORMAT
	L10N_DEFAULT_INPUT_DATEFORMAT
	MAX_VISUAL_URL_LENGTH

	Xml:
	XML_VALIDATION
	-->

</config>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/rep/config-darwin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: config-darwin.xml 3943 2008-04-27 09:09:02Z gbevin $
  -->

<!DOCTYPE config SYSTEM "/dtd/config.dtd">

<config>
	<param name="RIFE_HOME">/data/Workspace/rife/programs/unittests</param>
	<param name="TEMPLATE_GENERATION_PATH"><value name="RIFE_HOME"/>/build/templates</param>
	<param name="TEMP_PATH"><value name="RIFE_HOME"/>/tmp</param>
	<param name="ORACLE_CONNECT">jdbc:oracle:thin:@192.168.17.129:1521:uwyn</param>
	<param name="FIREBIRD_CONNECT">jdbc:firebirdsql:firebird/3050:/opt/firebird.gdb</param>
	
	<include file="rep/config-common.xml"/>
</config>

=== gbevin/rife/rife_v1_remaining/programs/gui/config/rep/gui_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: gui_config.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE config SYSTEM "/dtd/config.dtd">

<config>
	<param name="L10N_DEFAULT_RESOURCEBUNDLE">localization/uwyn</param>
	<param name="DRAG_TRANSPARENT">true</param>
	<param name="DRAG_OUTLINE">false</param>
	<param name="SCROLLING_FAST">true</param>
	<param name="SCROLLING_OUTLINE">false</param>
	<param name="GRID_SHOW">true</param>
	<param name="GRID_SNAP">true</param>
	<param name="GRID_SIZE">5</param>
</config>
