=== gbevin/rife/rife_v1_remaining/shared/dtd/element.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: element.dtd 3918 2008-04-14 17:35:35Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Element 1.6//EN
  -  SYSTEM ID: http://rifers.org/dtd/element_1_6.dtd
  -->

<!ELEMENT element		(property | exit | childtrigger | input | inbean | output | outbean | submission | incookie | outcookie | pathinfo)*>
<!ATTLIST element		implementation CDATA #IMPLIED
                        extends CDATA #IMPLIED
                        contenttype CDATA #IMPLIED
                        pathinfo (loose|strict) #IMPLIED>

<!ELEMENT property		(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST property		name CDATA #REQUIRED>

<!ELEMENT participant	(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST participant	name CDATA #REQUIRED>

<!ELEMENT datasource	(#PCDATA | config | participant)*>

<!ELEMENT template		(#PCDATA | config | participant)*>
<!ATTLIST template		type CDATA #IMPLIED>

<!ELEMENT exit			EMPTY>
<!ATTLIST exit			name CDATA #REQUIRED>

<!ELEMENT childtrigger	EMPTY>
<!ATTLIST childtrigger	name CDATA #REQUIRED>

<!ELEMENT input			(default*)>
<!ATTLIST input			name CDATA #REQUIRED>

<!ELEMENT inbean		EMPTY>
<!ATTLIST inbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT output		(default*)>
<!ATTLIST output		name CDATA #REQUIRED>

<!ELEMENT outbean		EMPTY>
<!ATTLIST outbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT submission	(param | bean | file)*>
<!ATTLIST submission	name CDATA #REQUIRED
						scope (local|global) "local"
						continuations (preserve|cancel) "preserve">

<!ELEMENT param			(default*)>
<!ATTLIST param			name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT bean			EMPTY>
<!ATTLIST bean			classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT file			EMPTY>
<!ATTLIST file		    name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT incookie		(default?)>
<!ATTLIST incookie		name CDATA #REQUIRED>

<!ELEMENT outcookie		(default?)>
<!ATTLIST outcookie		name CDATA #REQUIRED>

<!ELEMENT default		(#PCDATA | config)*>

<!ELEMENT config		EMPTY>
<!ATTLIST config		param CDATA #REQUIRED>

<!ELEMENT pathinfo		EMPTY>
<!ATTLIST pathinfo		mapping CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/submission/typed_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: typed_injection.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.submission.TypedInjection">
	<submission name="typed">
		<param name="paramstring1"/>
		<param name="paramstring2"/>
		<param name="paramint1"/>
		<param name="paramint2">
			<default>378</default>
		</param>
		<param name="paramlong1"/>
		<param name="paramlong2"/>
		<param name="paramdouble1"/>
		<param name="paramdouble2"/>
		<param name="paramfloat1"/>
		<param name="paramfloat2"/>
		<param name="parammultiple"/>
	</submission>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/submission/generatedurlpathinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: generatedurlpathinfo.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.submission.GeneratedurlPathinfo">
	<submission name="submission1">
		<param name="parameter"/>
	</submission>
	
	<submission name="submission2">
		<param name="login"/>
		<param name="password"/>
	</submission>
	
	<submission name="submission3">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<submission name="submission4"/>

	<submission name="submission5">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<submission name="submission6"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/authentication/database_authenticated_sessionduration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: database_authenticated_sessionduration.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="rife/authenticated/databaseunpurged.xml">
	<property name="datasource"><datasource><config param="sessiondurationunittestsdatasource"/></datasource></property>
	
	<property name="template_name">authentication_database</property>
	<property name="session_duration">2000</property>

	<submission name="credentials">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<childtrigger name="authid"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/cookies/defaults.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: defaults.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.cookies.Defaults">
	<incookie name="cookie1">
		<default>the first cookie</default>
	</incookie>
	<incookie name="cookie2"/>
	<incookie name="cookie3">
		<default><config param="ENGINE_ELEMENT_CONFIG_VALUE"/></default>
	</incookie>
	<outcookie name="cookie3"/>
	<outcookie name="cookie4">
		<default><config param="ENGINE_ELEMENT_CONFIG_VALUE"/></default>
	</outcookie>
	<outcookie name="cookie5">
		<default>the fifth cookie</default>
	</outcookie>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/authentication/purging_mixed_authenticated_remember.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: purging_mixed_authenticated_remember.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="rife/authenticated/mixed.xml">
	<property name="datasource"><datasource><config param="unittestsdatasource"/></datasource></property>

	<property name="sessionmanager_id">purging_mixed_pgsql</property>
	<property name="session_duration">1000</property>
	<property name="session_purge_frequency">1</property>
	<property name="session_purge_scale">1</property>

	<property name="remember_duration">2000</property>
	<property name="remember_purge_frequency">1</property>
	<property name="remember_purge_scale">1</property>

	<property name="template_name">authentication_remember</property>

	<submission name="credentials">
		<bean classname="com.uwyn.rife.authentication.credentials.RoleUser"/>
	</submission>

	<incookie name="rememberid"/>
	<outcookie name="rememberid"/>

	<childtrigger name="authid"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/extending/multiplelevels1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: multiplelevels1.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="element/extending/blueprint.xml">

	<property name="property3">value3</property>
	<property name="property4">value4</property>

	<input name="input3"/>
	<input name="input4">
		<default>inputdefault</default>
	</input>
	
	<incookie name="incookie3"/>
	<incookie name="incookie4">
		<default>incookiedefault</default>
	</incookie>

</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/exits/generatedform_source.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: generatedform_source.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.exits.GeneratedformSource">
	<input name="setoutputs"><default>1</default></input>
	<output name="output1"/>
	<output name="output2"/>
	<output name="output3"/>

	<exit name="exit1"/>
	<exit name="exit2"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/globals/source.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: source.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.globals.Source">
	<input name="switch"/>
	<input name="reflected"/>
	<input name="reflected_overridden"/>
	<input name="not_reflected"/>
	
	<exit name="exit1"/>
	<exit name="exit2"/>

	<output name="reflected"/>
	<output name="reflected_overridden"/>
</element>
