=== gbevin/rife/rife_v1_remaining/shared/dtd/element.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: element.dtd 3918 2008-04-14 17:35:35Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Element 1.6//EN
  -  SYSTEM ID: http://rifers.org/dtd/element_1_6.dtd
  -->

<!ELEMENT element		(property | exit | childtrigger | input | inbean | output | outbean | submission | incookie | outcookie | pathinfo)*>
<!ATTLIST element		implementation CDATA #IMPLIED
                        extends CDATA #IMPLIED
                        contenttype CDATA #IMPLIED
                        pathinfo (loose|strict) #IMPLIED>

<!ELEMENT property		(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST property		name CDATA #REQUIRED>

<!ELEMENT participant	(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST participant	name CDATA #REQUIRED>

<!ELEMENT datasource	(#PCDATA | config | participant)*>

<!ELEMENT template		(#PCDATA | config | participant)*>
<!ATTLIST template		type CDATA #IMPLIED>

<!ELEMENT exit			EMPTY>
<!ATTLIST exit			name CDATA #REQUIRED>

<!ELEMENT childtrigger	EMPTY>
<!ATTLIST childtrigger	name CDATA #REQUIRED>

<!ELEMENT input			(default*)>
<!ATTLIST input			name CDATA #REQUIRED>

<!ELEMENT inbean		EMPTY>
<!ATTLIST inbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT output		(default*)>
<!ATTLIST output		name CDATA #REQUIRED>

<!ELEMENT outbean		EMPTY>
<!ATTLIST outbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT submission	(param | bean | file)*>
<!ATTLIST submission	name CDATA #REQUIRED
						scope (local|global) "local"
						continuations (preserve|cancel) "preserve">

<!ELEMENT param			(default*)>
<!ATTLIST param			name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT bean			EMPTY>
<!ATTLIST bean			classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT file			EMPTY>
<!ATTLIST file		    name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT incookie		(default?)>
<!ATTLIST incookie		name CDATA #REQUIRED>

<!ELEMENT outcookie		(default?)>
<!ATTLIST outcookie		name CDATA #REQUIRED>

<!ELEMENT default		(#PCDATA | config)*>

<!ELEMENT config		EMPTY>
<!ATTLIST config		param CDATA #REQUIRED>

<!ELEMENT pathinfo		EMPTY>
<!ATTLIST pathinfo		mapping CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/authentication/mixed_authenticated_sessionduration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: mixed_authenticated_sessionduration.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="rife/authenticated/mixedunpurged.xml">
	<property name="datasource"><datasource><config param="unittestsdatasource"/></datasource></property>
	
	<property name="template_name">authentication_mixed</property>
	<property name="session_duration">2000</property>
	<property name="sessionmanager_id">session duration</property>

	<submission name="credentials">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<childtrigger name="authid"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/submission/params_defaults.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: params_defaults.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.submission.ParamsDefaults">
	<submission name="name">
		<param name="firstname">
			<default>John</default>
			<default>Paul</default>
		</param>
		<param name="lastname"/>
		<param name="age">
			<default>27</default>
		</param>
		<param name="configparam">
			<default><config param="ENGINE_ELEMENT_CONFIG_VALUE"/></default>
		</param>
	</submission>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/submission/multiple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: multiple.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.submission.Multiple">
	<submission name="login">
		<param name="login"/>
		<param name="password"/>
		<param name="language"/>
	</submission>
	<submission name="register">
		<param name="login"/>
		<param name="password"/>
		<param name="firstname"/>
		<param name="lastname"/>
	</submission>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/xml/test_xml2elementinfo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: test_xml2elementinfo1.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.engine.Simple">

	<!-- PROPERTIES -->
	<property name="property1">value1</property>
	<property name="property2">  <template type="enginehtml">noblocks_in</template> </property>
	<property name="property3"><participant name="configuration">
		EXPRESSION_CONFIG_VALUE</participant> 3 </property>
	<property name="property4">
		<datasource>
			unittests<participant name="configuration">  <config param="IOC_CONFIG"/>
			</participant>
		</datasource>
	</property>
	<property name="property5">
		<participant name="configuration">
			DATASOURCE_USER
		</participant>
		<participant name="configuration"><config param="IOC_CONFIG"/></participant>
	</property>
	<property name="property6">
		<participant name="doesntexist">
			unittests<participant name="configuration">  <config param="IOC_CONFIG"/>
			</participant>
		</participant>
	</property>
	<property name="property7"><template type="unknowntype">noblocks_in</template></property>

	<!-- INPUTS -->
	<input name="input1"/>
	<input name="input2"/>
	<input name="input3"/>
	
	<!-- OUTPUTS -->
	<output name="output1"/>
	<output name="output2"/>
	<output name="output3"/>
	<output name="output4"/>
	
	<!-- INCOOKIES -->
	<incookie name="incookie1"/>
	<incookie name="incookie2"/>
	
	<!-- OUTCOOKIES -->
	<outcookie name="outcookie1"/>
	<outcookie name="outcookie2"/>
	<outcookie name="outcookie3"/>
	<outcookie name="outcookie4"/>
	
	<!-- INBEANS -->
	<inbean name="inbean1" classname="com.uwyn.rife.engine.testelements.exits.BeanImpl1"/>
	<inbean classname="com.uwyn.rife.engine.testelements.exits.BeanImpl2"/>
	<inbean classname="com.uwyn.rife.engine.testelements.exits.BeanImpl1" prefix="prefix_"/>
	<inbean name="inbean2" classname="com.uwyn.rife.engine.testelements.submission.BeanImpl" prefix="prefixgroup_" group="somegroup"/>
	<inbean classname="com.uwyn.rife.engine.testelements.submission.BeanImpl" group="somegroup"/>
	
	<!-- OUTBEANS -->
	<outbean classname="com.uwyn.rife.engine.testelements.exits.BeanImpl1"/>
	<outbean classname="com.uwyn.rife.engine.testelements.exits.BeanImpl2"/>
	<outbean name="outbean1" classname="com.uwyn.rife.engine.testelements.exits.BeanImpl2" prefix="prefix_"/>
	<outbean classname="com.uwyn.rife.engine.testelements.submission.BeanImpl" prefix="prefixgroup_" group="somegroup"/>
	<outbean name="outbean2" classname="com.uwyn.rife.engine.testelements.submission.BeanImpl" group="somegroup"/>
	
	<!-- CHILD TRIGGERS -->
	<childtrigger name="input1"/>
	<childtrigger name="input2"/>
	
	<!-- EXITS -->
	<exit name="exit1"/>
	<exit name="exit2"/>
	<exit name="exit3"/>
	<exit name="exit4"/>

    <!-- SUBMISSIONS -->
    <submission name="submission1">
        <param name="param1"/>
        <param name="param2"/>
        <param name="param3"/>
        <param regexp="paramA(\d+)"/>
        <param regexp="paramB(\d+)"/>
        <file name="file1"/>
        <file name="file2"/>
    </submission>
    <submission name="submission2">
        <param name="param1"/>
        <param name="param2"/>
        <param regexp="paramC(.*)"/>
        <file name="file1"/>
    </submission>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/subsites/globalexit/isolation/globaldestsource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: globaldestsource.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element implementation="com.uwyn.rife.engine.testelements.subsites.globalexit.isolation.GlobalDestSource">
	<input name="sourceinput1"/>
	<input name="sourceinput2">
		<default>default input value 2</default>
	</input>
	<input name="sourceinput3"/>

	<output name="sourceoutput1"/>
	<output name="sourceoutput2"/>
	<output name="sourceoutput3">
		<default>default output value 3</default>
	</output>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/authentication/purging_database_authenticated_encrypted.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: purging_database_authenticated_encrypted.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="rife/authenticated/database.xml">
	<property name="datasource"><datasource><config param="purgingunittestsdatasource"/></datasource></property>

	<property name="credentialsmanager_id">encrypted</property>
	<property name="template_name">authentication_database</property>
	<property name="password_encryption">SHA</property>
	<property name="session_duration">2000</property>
	<property name="session_purge_frequency">1</property>
	<property name="session_purge_scale">1</property>

	<submission name="credentials">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<childtrigger name="authid"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/authentication/memory_authenticated_sessionduration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: memory_authenticated_sessionduration.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="rife/authenticated/memoryunpurged.xml">
	<property name="template_name">authentication_memory</property>
	<property name="session_duration">2000</property>
	<property name="sessionmanager_id">session duration</property>

	<submission name="credentials">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<childtrigger name="authid"/>
</element>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/element/authentication/mixed_authenticated_encrypted.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: mixed_authenticated_encrypted.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE element SYSTEM "/dtd/element.dtd">

<element extends="rife/authenticated/mixedunpurged.xml">
	<property name="datasource"><datasource><config param="unittestsdatasource"/></datasource></property>
	
	<property name="credentialsmanager_id">encrypted</property>
	<property name="template_name">authentication_mixed</property>
	<property name="password_encryption">SHA</property>

	<submission name="credentials">
		<param name="login"/>
		<param name="password"/>
	</submission>

	<childtrigger name="authid"/>
</element>
