=== gbevin/rife/rife_v1_remaining/shared/dtd/scheduler.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: scheduler.dtd 3918 2008-04-14 17:35:35Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Scheduler 1.0//EN
  -  SYSTEM ID: http://rifers.org/dtd/scheduler_1_0.dtd
  -->

<!ELEMENT scheduler	(task*,executor*)>

<!ELEMENT task		(option)*>
<!ATTLIST task		classname NMTOKEN #IMPLIED
					planned CDATA #IMPLIED
					frequency CDATA #IMPLIED
					type CDATA #IMPLIED>
					
<!ELEMENT option	(#PCDATA | config)*>
<!ATTLIST option	name CDATA #REQUIRED>

<!ELEMENT executor	EMPTY>
<!ATTLIST executor	classname NMTOKEN #IMPLIED>

<!ELEMENT config	EMPTY>
<!ATTLIST config	param CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/xml/test_xml2scheduler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: test_xml2scheduler.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE scheduler SYSTEM "/dtd/scheduler.dtd">

<scheduler>
	<task classname="com.uwyn.rife.scheduler.TestExecutor"/>
	<task type="test_executor2"/>
	<task classname="com.uwyn.rife.scheduler.TestExecutor" planned="2002/9/10 17:10">
		<option name="option1">value1</option>
		<option name="option2"><config param="scheduler_value"/></option>
	</task>
	<task classname="com.uwyn.rife.scheduler.TestExecutor" frequency="0 9 * * 1"/>
	<task type="test_executor2" planned="2002/7/7 10:12" frequency="*/10 9 15 * *"/>
	
	<executor classname="com.uwyn.rife.scheduler.TestExecutor2"/>
</scheduler>
