=== gbevin/rife/rife_v1_remaining/shared/dtd/site.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: site.dtd 3930 2008-04-24 11:10:22Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Site 1.6.2//EN
  -  SYSTEM ID: http://rifers.org/dtd/site_1_6_2.dtd
  -->

<!ELEMENT site			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST site	    	fallbackid CDATA #IMPLIED>

<!ELEMENT group			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | errorhandler)*>
<!ATTLIST group			inherits CDATA #IMPLIED
						pre CDATA #IMPLIED>

<!ELEMENT state			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST state			store CDATA #IMPLIED> <!-- by default the "query" and "session" state stores are supported -->

<!ELEMENT globalvar		(default*)>
<!ATTLIST globalvar	    name CDATA #REQUIRED>

<!ELEMENT globalcookie	(default*)>
<!ATTLIST globalcookie	name CDATA #REQUIRED>

<!ELEMENT globalbean	EMPTY>
<!ATTLIST globalbean	classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT globalexit	EMPTY>
<!ATTLIST globalexit    name CDATA #REQUIRED
						destid CDATA #IMPLIED
						reflect (0|f|false|1|t|true) "false"
						snapback (0|f|false|1|t|true) "false"
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT arrival		EMPTY>
<!ATTLIST arrival    	destid CDATA #REQUIRED
						redirect (0|f|false|1|t|true) "false">

<!ELEMENT departure		EMPTY>
<!ATTLIST departure    	srcid CDATA #REQUIRED>

<!ELEMENT errorhandler	(type*)>
<!ATTLIST errorhandler	destid CDATA #REQUIRED>

<!ELEMENT type			EMPTY>
<!ATTLIST type	    	classname CDATA #REQUIRED>

<!ELEMENT subsite		(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST subsite		id ID #REQUIRED
						file CDATA #IMPLIED
						urlprefix CDATA #IMPLIED
						inherits CDATA #IMPLIED
						pre CDATA #IMPLIED>

<!ELEMENT default		(#PCDATA | config)*>

<!ELEMENT config	    EMPTY>
<!ATTLIST config	    param CDATA #REQUIRED>

<!ELEMENT element		(property | datalink | flowlink | autolink | exit | childtrigger | input | inbean | output | outbean | submission | incookie | outcookie | pathinfo)*>
<!ATTLIST element		file CDATA #IMPLIED
						id ID #IMPLIED
						url CDATA #IMPLIED
						inherits CDATA #IMPLIED
						pre CDATA #IMPLIED
						implementation CDATA #IMPLIED
                        extends CDATA #IMPLIED
                        contenttype CDATA #IMPLIED
                        pathinfo (loose|strict) #IMPLIED>

<!ELEMENT property		(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST property		name CDATA #REQUIRED>

<!ELEMENT participant	(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST participant	name CDATA #REQUIRED>

<!ELEMENT datasource	(#PCDATA | config | participant)*>

<!ELEMENT template		(#PCDATA | config | participant)*>
<!ATTLIST template		type CDATA #IMPLIED>

<!ELEMENT datalink		EMPTY>
<!ATTLIST datalink		srcoutput CDATA #IMPLIED
						srcoutbean CDATA #IMPLIED
						destid CDATA #IMPLIED
						snapback (0|f|false|1|t|true) "false"
						destinput CDATA #IMPLIED
						destinbean CDATA #IMPLIED>

<!ELEMENT flowlink		(datalink)*>
<!ATTLIST flowlink		srcexit CDATA #REQUIRED
						destid CDATA #IMPLIED
						snapback (0|f|false|1|t|true) "false"
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT autolink		(datalink)*>
<!ATTLIST autolink		srcexit CDATA #REQUIRED
						destid CDATA #IMPLIED
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT exit			EMPTY>
<!ATTLIST exit			name CDATA #REQUIRED>

<!ELEMENT childtrigger	EMPTY>
<!ATTLIST childtrigger	name CDATA #REQUIRED>

<!ELEMENT input			(default*)>
<!ATTLIST input			name CDATA #REQUIRED>

<!ELEMENT inbean		EMPTY>
<!ATTLIST inbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT output		(default*)>
<!ATTLIST output		name CDATA #REQUIRED>

<!ELEMENT outbean		EMPTY>
<!ATTLIST outbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT submission	(param | bean | file)*>
<!ATTLIST submission	name CDATA #REQUIRED
						scope (local|global) "local"
						continuations (preserve|cancel) "preserve">

<!ELEMENT param			(default*)>
<!ATTLIST param			name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT bean			EMPTY>
<!ATTLIST bean			classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT file			EMPTY>
<!ATTLIST file		    name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT incookie		(default?)>
<!ATTLIST incookie		name CDATA #REQUIRED>

<!ELEMENT outcookie		(default?)>
<!ATTLIST outcookie		name CDATA #REQUIRED>

<!ELEMENT pathinfo		EMPTY>
<!ATTLIST pathinfo		mapping CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/authentication_database.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: authentication_database.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalvar name="authid"/>

	<!-- database authenticated /-->
	<element id="DATABASE_AUTHENTICATED_BASIC" file="element/authentication/database_authenticated_basic.xml"/>
	<element id="DATABASE_LOGOUT_TEMPLATE_BASIC" file="element/authentication/database_logout_template_basic.xml" url="/authentication/database/logout/template/basic"/>
	<element id="DATABASE_LOGOUT_PASSTHROUGH_BASIC" file="element/authentication/database_logout_passthrough.xml">
		<flowlink srcexit="logged_out" snapback="true"/>
	</element>
	<element id="DATABASE_AUTHENTICATED_BASIC_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/basic" inherits="DATABASE_AUTHENTICATED_BASIC">
		<flowlink srcexit="reload" destid="DATABASE_AUTHENTICATED_BASIC_TARGET"/>
		<flowlink srcexit="logout_template" destid="DATABASE_LOGOUT_TEMPLATE_BASIC"/>
		<flowlink srcexit="logout_passthrough" destid="DATABASE_LOGOUT_PASSTHROUGH_BASIC"/>
	</element>

	<!-- database authenticated logout precedence -->
	<element id="DATABASE_AUTHENTICATED_PRECEDENCE" file="element/authentication/database_authenticated_precedence.xml"/>
	<element id="DATABASE_LOGOUT_PRECEDENCE_CHECK" file="element/authentication/database_logout_precedence_check.xml">
		<flowlink srcexit="logout" destid="DATABASE_LOGOUT_PRECEDENCE_PASSTHROUGH"/>
	</element>
	<element id="DATABASE_LOGOUT_PRECEDENCE_PASSTHROUGH" file="element/authentication/database_logout_passthrough.xml">
		<flowlink srcexit="logged_out" snapback="true"/>
	</element>
	<element id="DATABASE_AUTHENTICATED_PRECEDENCE_TARGET" file="element/authentication/database_authenticated_precedence_target.xml" url="/authentication/database/precedence" inherits="DATABASE_AUTHENTICATED_PRECEDENCE" pre="DATABASE_LOGOUT_PRECEDENCE_CHECK">
		<flowlink srcexit="reload" destid="DATABASE_AUTHENTICATED_PRECEDENCE_TARGET"/>
	</element>
	
	<!-- checking password encryption -->
	<element id="DATABASE_AUTHENTICATED_ENCRYPTED" file="element/authentication/database_authenticated_encrypted.xml"/>
	<element id="DATABASE_AUTHENTICATED_ENCRYPTED_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/encrypted" inherits="DATABASE_AUTHENTICATED_ENCRYPTED"/>

	<!-- using roles -->
	<element id="DATABASE_AUTHENTICATED_ROLE" file="element/authentication/database_authenticated_role.xml"/>
	<element id="DATABASE_AUTHENTICATED_ROLE_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/role" inherits="DATABASE_AUTHENTICATED_ROLE"/>
	
	<element id="DATABASE_AUTHENTICATED_ROLE2" file="element/authentication/database_authenticated_role2.xml"/>
	<element id="DATABASE_AUTHENTICATED_ROLE2_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/role2" inherits="DATABASE_AUTHENTICATED_ROLE2"/>

	<!-- checking session timeout -->
	<element id="DATABASE_AUTHENTICATED_SESSIONDURATION" file="element/authentication/database_authenticated_sessionduration.xml"/>
	<element id="DATABASE_AUTHENTICATED_SESSIONDURATION_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/sessionduration" inherits="DATABASE_AUTHENTICATED_SESSIONDURATION"/>

	<!-- checking non-enforced authentication -->
	<element id="DATABASE_AUTHENTICATED_ENFORCE" file="element/authentication/database_authenticated_enforce.xml"/>
	<element id="DATABASE_AUTHENTICATED_ENFORCE2" file="element/authentication/database_authenticated_enforce2.xml"/>
	<element id="DATABASE_AUTHENTICATED_ENFORCE_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/enforce" inherits="DATABASE_AUTHENTICATED_ENFORCE"/>
	<element id="DATABASE_AUTHENTICATED_ENFORCE2_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/enforce2" inherits="DATABASE_AUTHENTICATED_ENFORCE2"/>

	<!-- using remember me /-->
	<element id="DATABASE_AUTHENTICATED_REMEMBER" file="element/authentication/database_authenticated_remember.xml"/>
	<element id="DATABASE_AUTHENTICATED_REMEMBER_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/remember" inherits="DATABASE_AUTHENTICATED_REMEMBER">
		<flowlink srcexit="reload" destid="DATABASE_AUTHENTICATED_REMEMBER_TARGET"/>
		<flowlink srcexit="logout_template" destid="DATABASE_LOGOUT_TEMPLATE_BASIC"/>
		<flowlink srcexit="logout_passthrough" destid="DATABASE_LOGOUT_PASSTHROUGH_BASIC"/>
	</element>

	<!-- testing prohibited remembered authentication /-->
	<element id="DATABASE_AUTHENTICATED_PROHIBITREMEMBERED" file="element/authentication/database_authenticated_prohibitremember.xml"/>
	<element id="DATABASE_AUTHENTICATED_PROHIBITREMEMBERED_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/database/prohibitremember" inherits="DATABASE_AUTHENTICATED_PROHIBITREMEMBERED">
		<flowlink srcexit="reload" destid="DATABASE_AUTHENTICATED_PROHIBITREMEMBERED_TARGET"/>
		<flowlink srcexit="logout_template" destid="DATABASE_LOGOUT_TEMPLATE_BASIC"/>
		<flowlink srcexit="logout_passthrough" destid="DATABASE_LOGOUT_PASSTHROUGH_BASIC"/>
	</element>
	
	<!-- mixed authenticated /-->
	<element id="MIXED_AUTHENTICATED_BASIC" file="element/authentication/mixed_authenticated_basic.xml"/>
	<element id="MIXED_AUTHENTICATED_BASIC_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/mixed/basic" inherits="MIXED_AUTHENTICATED_BASIC"/>

	<element id="MIXED_AUTHENTICATED_ENCRYPTED" file="element/authentication/mixed_authenticated_encrypted.xml"/>
	<element id="MIXED_AUTHENTICATED_ENCRYPTED_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/mixed/encrypted" inherits="MIXED_AUTHENTICATED_ENCRYPTED"/>

	<element id="MIXED_AUTHENTICATED_OTHERID" file="element/authentication/mixed_authenticated_otherid.xml"/>
	<element id="MIXED_AUTHENTICATED_OTHERID_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/mixed/otherid" inherits="MIXED_AUTHENTICATED_OTHERID"/>

	<element id="MIXED_AUTHENTICATED_ROLE" file="element/authentication/mixed_authenticated_role.xml"/>
	<element id="MIXED_AUTHENTICATED_ROLE_TARGET" file="element/authentication/mixed_authenticated_target.xml" url="/authentication/mixed/role" inherits="MIXED_AUTHENTICATED_ROLE"/>
	
	<element id="MIXED_AUTHENTICATED_ROLE2" file="element/authentication/mixed_authenticated_role2.xml"/>
	<element id="MIXED_AUTHENTICATED_ROLE2_TARGET" file="element/authentication/mixed_authenticated_target.xml" url="/authentication/mixed/role2" inherits="MIXED_AUTHENTICATED_ROLE2"/>

	<element id="MIXED_AUTHENTICATED_SESSIONDURATION" file="element/authentication/mixed_authenticated_sessionduration.xml"/>
	<element id="MIXED_AUTHENTICATED_SESSIONDURATION_TARGET" file="element/authentication/database_authenticated_target.xml" url="/authentication/mixed/sessionduration" inherits="MIXED_AUTHENTICATED_SESSIONDURATION"/>

	<!-- purging database authenticated /-->
	<element id="PURGING_DATABASE_AUTHENTICATED_BASIC" file="element/authentication/purging_database_authenticated_basic.xml"/>
	<element id="PURGING_DATABASE_AUTHENTICATED_BASIC_TARGET" file="element/authentication/purging_database_authenticated_target.xml" url="/authentication/purging/database/basic" inherits="PURGING_DATABASE_AUTHENTICATED_BASIC"/>
	<element id="PURGING_DATABASE_AUTHENTICATED_ENCRYPTED" file="element/authentication/purging_database_authenticated_encrypted.xml"/>
	<element id="PURGING_DATABASE_AUTHENTICATED_ENCRYPTED_TARGET" file="element/authentication/purging_database_authenticated_target.xml" url="/authentication/purging/database/encrypted" inherits="PURGING_DATABASE_AUTHENTICATED_ENCRYPTED"/>
	<element id="PURGING_DATABASE_AUTHENTICATED_REMEMBER" file="element/authentication/purging_database_authenticated_remember.xml"/>
	<element id="PURGING_DATABASE_AUTHENTICATED_REMEMBER_TARGET" file="element/authentication/purging_database_authenticated_target.xml" url="/authentication/purging/database/remember" inherits="PURGING_DATABASE_AUTHENTICATED_REMEMBER"/>

	<!-- purging mixed authenticated /-->
	<element id="PURGING_MIXED_AUTHENTICATED_BASIC" file="element/authentication/purging_mixed_authenticated_basic.xml"/>
	<element id="PURGING_MIXED_AUTHENTICATED_BASIC_TARGET" file="element/authentication/purging_database_authenticated_target.xml" url="/authentication/purging/mixed/basic" inherits="PURGING_MIXED_AUTHENTICATED_BASIC"/>
	<element id="PURGING_MIXED_AUTHENTICATED_ENCRYPTED" file="element/authentication/purging_mixed_authenticated_encrypted.xml"/>
	<element id="PURGING_MIXED_AUTHENTICATED_ENCRYPTED_TARGET" file="element/authentication/purging_database_authenticated_target.xml" url="/authentication/purging/mixed/encrypted" inherits="PURGING_MIXED_AUTHENTICATED_ENCRYPTED"/>
	<element id="PURGING_MIXED_AUTHENTICATED_REMEMBER" file="element/authentication/purging_mixed_authenticated_remember.xml"/>
	<element id="PURGING_MIXED_AUTHENTICATED_REMEMBER_TARGET" file="element/authentication/purging_database_authenticated_target.xml" url="/authentication/purging/mixed/remember" inherits="PURGING_MIXED_AUTHENTICATED_REMEMBER"/>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/subsite/departure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: departure.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalvar name="globalvar_departure1">
		<default>some</default>
		<default>values</default>
	</globalvar>
	<globalvar name="globalvar_departure2">
		<default>another value</default>
	</globalvar>
	<globalvar name="globalvar_departure3"/>
	<departure srcid="DEPARTURE_SOURCE"/>
	
	<element id="DEPARTURE_SOURCE" file="element/subsites/departure/source.xml" url="/source">
		<flowlink srcexit="target" destid="DEPARTURE_TARGET"/>
		<datalink srcoutput="output1" destid="DEPARTURE_TARGET" destinput="input1"/>
		<datalink srcoutput="output2" destid="DEPARTURE_TARGET" destinput="input2"/>
		<datalink srcoutput="globalvar_departure2" destid="DEPARTURE_TARGET" destinput="input3"/>
	</element>
	<element id="DEPARTURE_TARGET" file="element/subsites/departure/target.xml" url="/target"/>
</site>

=== gbevin/rife/rife_v1_remaining/src/examples/tutorial/06_inheritance/src/sites/inheritance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: inheritance.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<arrival destid="Home"/>

	<group>
		<!-- This global variable is available throughout the site to indicate
		     whether an element's content should first be surrounded by frames
		     or shown directly -->
		<globalvar name="show_content"/>
		
		<!-- The element structure that creates the frameset of the site.
			 It is meant to be be inherited from by all content elements that
			 should be surrounded by frames. Automatically a main frameset will
			 be created with a top navigation frame and the actual element
			 content will be present in a bottom content frame.
			 -->
		<element id="FrameMain" file="frames/main.xml">
			<flowlink srcexit="navigation" destid="FrameNavigation" inheritance="cancel"/>
			<flowlink srcexit="content" destid="FrameMain">
				<datalink srcoutput="show_content" destinput="show_content"/>
			</flowlink>
		</element>
		
		<element id="FrameNavigation" file="frames/navigation.xml" url="/navigation">
			<flowlink srcexit="more" destid="More"/>
			<flowlink srcexit="home" destid="Home"/>
			<flowlink srcexit="standalone" destid="Standalone"/>
		</element>
		
		<!-- The actual content elements of the site that will be surrounded
			 by the frames when they're accessed at their mapping url -->
		<element id="Home" extends="rife/template/print.xml" url="/home" inherits="FrameMain">
			<property name="name">home</property>
			<exit name="next"/>
			
			<flowlink srcexit="next" destid="More"/>
		</element>
		
		<element id="More" extends="rife/template/print.xml" url="/more" inherits="FrameMain">
			<property name="name">more</property>
			<exit name="next"/>
			
			<flowlink srcexit="next" destid="Standalone"/>
		</element>
		
		<!-- This element provides regular top-level content and just doesn't
			 inherit from the frames structure -->
		<element id="Standalone" extends="rife/template/print.xml" url="/standalone">
			<property name="name">standalone</property>
			<exit name="next"/>
			
			<flowlink srcexit="next" destid="Home"/>
		</element>
	</group>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/xml/test_xml2site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: test_xml2site.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site fallbackid="ELEMENT4">
	<globalexit name="globalexit1" destid="ELEMENT6"/>
	<globalexit name="globalexit2" destid="SUBSITE.ELEMENT2"/>

	<globalvar name="globalvar1"/>
	<globalvar name="globalvar2"/>
	
	<globalbean name="globalbean1" classname="com.uwyn.rife.engine.testelements.submission.BeanImpl" prefix="onemoreprefixgroup_" group="anothergroup"/>
	<globalbean classname="com.uwyn.rife.engine.testelements.submission.BeanImpl" group="anothergroup"/>

	<property name="prop1">sitepropval</property>
	<property name="prop6">
		<datasource>
			purgingunittests<participant name="configuration">  <config param="IOC_CONFIG"/>
			</participant>
		</datasource>
	</property>
 
 	<subsite id="SUBSITE" file="xml/test_xml2sitesubsite.xml" urlprefix="/subsite" inherits="ELEMENT4">
		<property name="prop1">subsitepropval</property>
		<property name="prop2">  <template type="enginehtml">noblocks_in</template> </property>
		<property name="prop3"><participant name="configuration">
			EXPRESSION_CONFIG_VALUE</participant> 3 </property>
		<property name="prop4">
			<datasource>
				unittests<participant name="configuration">  <config param="IOC_CONFIG"/>
				</participant>
			</datasource>
		</property>
		<property name="prop5">
			<participant name="configuration">
				DATASOURCE_USER
			</participant>
			<participant name="configuration"><config param="IOC_CONFIG"/></participant>
		</property>
	</subsite>
	
	<group inherits="ELEMENT5">
		<globalvar name="globalvar4"/>
 	
		<element id="ELEMENT6" file="xml/test_xml2elementinfo2.xml" url="/test/element6" inherits="ELEMENT3"/>
		<element file="xml/test_xml2elementinfo3.xml" url="/test/element7"/>
	</group>
	
	<element id="ELEMENT1" file="xml/test_xml2elementinfo1.xml" url="/test/element1">
		<datalink srcoutput="output1" destid="ELEMENT2" destinput="input1"/>
		<datalink srcoutput="output1" destid="ELEMENT2" destinput="input2"/>
		<flowlink srcexit="exit1" destid="ELEMENT2"/>
		<flowlink srcexit="exit2" snapback="true"/>
		<datalink srcoutput="output2" snapback="t" destinput="input2"/>
		
		<flowlink srcexit="exit3" destid="ELEMENT2">
			<datalink srcoutput="output3" destinput="input1"/>
		</flowlink>
		
		<flowlink srcexit="exit4" destid="ELEMENT2">
			<datalink srcoutput="output4" destinput="input1"/>
		</flowlink>

		<property name="prop1">elementpropval</property>
		<property name="prop7">
			<datasource>
				sessiondurationunittests<participant name="configuration">  <config param="IOC_CONFIG"/>
				</participant>
			</datasource>
		</property>
	</element>
	
	<property name="prop2">  <template type="enginehtml">unsetvalues_output_in</template> </property>

	<element id="ELEMENT2" file="xml/test_xml2elementinfo2.xml" inherits="ELEMENT3" url="/test/element2"/>
			 
	<element id="ELEMENT3" file="xml/test_xml2elementinfo3.xml"/>

	<element id="ELEMENT4" file="xml/test_xml2elementinfo4.xml"/>

	<element id="ELEMENT5" file="xml/test_xml2elementinfo5.xml"/>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/subsite/globalexit/isolation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: isolation.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalvar name="globalvar2">
		<default>subsite value2</default>
	</globalvar>

	<globalexit name="globalexit3" destid="GLOBALDEST3"/>
	
	<element id="GLOBALDEST3" file="element/subsites/globalexit/isolation/globaldesttarget.xml" url="/globaldesttarget"/>

	<element id="GLOBALDESTSOURCE" file="element/subsites/globalexit/isolation/globaldestsource.xml" url="/globaldestsource">
		<datalink srcoutput="sourceoutput1" destid=".GLOBALDEST1" destinput="destinput1"/>
		<datalink srcoutput="sourceoutput2" destid=".GLOBALDEST1" destinput="destinput2"/>
		<datalink srcoutput="sourceoutput3" destid=".GLOBALDEST1" destinput="destinput3"/>
	</element>
</site>

=== gbevin/rife/rife_v1_remaining/src/examples/tutorial/05_friends_basic/src/sites/friends.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: friends.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
    <arrival destid="Menu"/>
	
   	<globalexit name="menu" destid="Menu"/>
    
    <element id="Display" implementation="tutorial.friends.Display" url="/display"/>

    <element id="Menu" extends="rife/template/print.xml" url="/menu">
		<property name="name">menu</property>
		
		<exit name="install"/>
		<exit name="add"/>
		<exit name="remove"/>
		<exit name="display"/>
	
        <flowlink srcexit="install" destid="Install"/>
        <flowlink srcexit="add" destid="Add"/>
        <flowlink srcexit="remove" destid="Remove"/>
        <flowlink srcexit="display" destid="Display"/>
    </element>
    
	<element id="Install" file="install.xml" url="/install"/>
	<element id="Add" file="add.xml" url="/add"/>
	<element id="Remove" file="remove.xml" url="/remove"/>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/cookies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: cookies.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalcookie name="globalcookie1"/>
	<globalcookie name="globalcookie2">
		<default>globalcookievalue2</default>
	</globalcookie>
	<globalcookie name="globalcookie3"/>
	
	<element id="COOKIES_VALID_SOURCE" url="/cookies/valid/source" file="element/cookies/valid_source.xml"/>
	<element id="COOKIES_VALID_DESTINATION" url="/cookies/valid/destination" file="element/cookies/valid_destination.xml"/>
	
	<element id="COOKIES_VALID_SOURCE_BIJECTION" url="/cookies/valid/source/bijection" implementation="com.uwyn.rife.engine.testelements.cookies.SourceBijection" extends="element/cookies/valid_source.xml"/>

	<element id="COOKIES_INVALID_SOURCE" url="/cookies/invalid/source" file="element/cookies/invalid_source.xml"/>
	<element id="COOKIES_INVALID_DESTINATION" url="/cookies/invalid/destination" file="element/cookies/invalid_destination.xml"/>

	<element id="COOKIES_DEFAULTS" url="/cookies/defaults" file="element/cookies/defaults.xml"/>

	<element id="INCOOKIES_GENERATED" file="element/cookies/incookiesgenerated.xml" url="/incookies/generated"/>

	<element id="INCOOKIES_INJECTION" implementation="com.uwyn.rife.engine.testelements.cookies.IncookiesInjection" extends="element/cookies/incookiesgenerated.xml" url="/incookies/injection"/>

	<element id="OUTCOOKIES_GENERATED" file="element/cookies/outcookiesgenerated.xml" url="/outcookies/generated"/>

	<element id="OUTCOOKIES_OUTJECTION" implementation="com.uwyn.rife.engine.testelements.cookies.OutcookiesOutjection" extends="element/cookies/outcookiesgenerated.xml" url="/outcookies/outjection"/>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/subsite/inheritance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: inheritance.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<element id="PARENT1" file="element/subsites/inheritance/parent1.xml"/>
	<element id="PARENT2" file="element/subsites/inheritance/parent2.xml"/>
	<element id="PARENT3" file="element/subsites/inheritance/parent3.xml" inherits="PARENT2"/>

	<subsite id="SINGLE" file="site/subsite/inheritance/single.xml" urlprefix="/single"/>
	
	<subsite id="STACK" file="site/subsite/inheritance/stack.xml" urlprefix="/stack" inherits="PARENT1"/>
	
	<subsite id="REPEATEDSTACK" file="site/subsite/inheritance/stack.xml" urlprefix="/repeatedstack" inherits="PARENT3"/>
	
	<subsite id="PARENTSUBSITE" file="site/subsite/inheritance/parent.xml" urlprefix="/parent"/>
	<subsite id="CHILDSUBSITE" file="site/subsite/inheritance/stack.xml" urlprefix="/parent/childsubsite" inherits="PARENTSUBSITE"/>
	<element id="CHILDELEMENT" file="element/subsites/inheritance/stack/targetchild.xml" url="/parent/childelement" inherits="PARENTSUBSITE"/>
</site>
