=== gbevin/rife/rife_v1_remaining/shared/dtd/site.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: site.dtd 3930 2008-04-24 11:10:22Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Site 1.6.2//EN
  -  SYSTEM ID: http://rifers.org/dtd/site_1_6_2.dtd
  -->

<!ELEMENT site			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST site	    	fallbackid CDATA #IMPLIED>

<!ELEMENT group			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | errorhandler)*>
<!ATTLIST group			inherits CDATA #IMPLIED
						pre CDATA #IMPLIED>

<!ELEMENT state			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST state			store CDATA #IMPLIED> <!-- by default the "query" and "session" state stores are supported -->

<!ELEMENT globalvar		(default*)>
<!ATTLIST globalvar	    name CDATA #REQUIRED>

<!ELEMENT globalcookie	(default*)>
<!ATTLIST globalcookie	name CDATA #REQUIRED>

<!ELEMENT globalbean	EMPTY>
<!ATTLIST globalbean	classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT globalexit	EMPTY>
<!ATTLIST globalexit    name CDATA #REQUIRED
						destid CDATA #IMPLIED
						reflect (0|f|false|1|t|true) "false"
						snapback (0|f|false|1|t|true) "false"
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT arrival		EMPTY>
<!ATTLIST arrival    	destid CDATA #REQUIRED
						redirect (0|f|false|1|t|true) "false">

<!ELEMENT departure		EMPTY>
<!ATTLIST departure    	srcid CDATA #REQUIRED>

<!ELEMENT errorhandler	(type*)>
<!ATTLIST errorhandler	destid CDATA #REQUIRED>

<!ELEMENT type			EMPTY>
<!ATTLIST type	    	classname CDATA #REQUIRED>

<!ELEMENT subsite		(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST subsite		id ID #REQUIRED
						file CDATA #IMPLIED
						urlprefix CDATA #IMPLIED
						inherits CDATA #IMPLIED
						pre CDATA #IMPLIED>

<!ELEMENT default		(#PCDATA | config)*>

<!ELEMENT config	    EMPTY>
<!ATTLIST config	    param CDATA #REQUIRED>

<!ELEMENT element		(property | datalink | flowlink | autolink | exit | childtrigger | input | inbean | output | outbean | submission | incookie | outcookie | pathinfo)*>
<!ATTLIST element		file CDATA #IMPLIED
						id ID #IMPLIED
						url CDATA #IMPLIED
						inherits CDATA #IMPLIED
						pre CDATA #IMPLIED
						implementation CDATA #IMPLIED
                        extends CDATA #IMPLIED
                        contenttype CDATA #IMPLIED
                        pathinfo (loose|strict) #IMPLIED>

<!ELEMENT property		(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST property		name CDATA #REQUIRED>

<!ELEMENT participant	(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST participant	name CDATA #REQUIRED>

<!ELEMENT datasource	(#PCDATA | config | participant)*>

<!ELEMENT template		(#PCDATA | config | participant)*>
<!ATTLIST template		type CDATA #IMPLIED>

<!ELEMENT datalink		EMPTY>
<!ATTLIST datalink		srcoutput CDATA #IMPLIED
						srcoutbean CDATA #IMPLIED
						destid CDATA #IMPLIED
						snapback (0|f|false|1|t|true) "false"
						destinput CDATA #IMPLIED
						destinbean CDATA #IMPLIED>

<!ELEMENT flowlink		(datalink)*>
<!ATTLIST flowlink		srcexit CDATA #REQUIRED
						destid CDATA #IMPLIED
						snapback (0|f|false|1|t|true) "false"
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT autolink		(datalink)*>
<!ATTLIST autolink		srcexit CDATA #REQUIRED
						destid CDATA #IMPLIED
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT exit			EMPTY>
<!ATTLIST exit			name CDATA #REQUIRED>

<!ELEMENT childtrigger	EMPTY>
<!ATTLIST childtrigger	name CDATA #REQUIRED>

<!ELEMENT input			(default*)>
<!ATTLIST input			name CDATA #REQUIRED>

<!ELEMENT inbean		EMPTY>
<!ATTLIST inbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT output		(default*)>
<!ATTLIST output		name CDATA #REQUIRED>

<!ELEMENT outbean		EMPTY>
<!ATTLIST outbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT submission	(param | bean | file)*>
<!ATTLIST submission	name CDATA #REQUIRED
						scope (local|global) "local"
						continuations (preserve|cancel) "preserve">

<!ELEMENT param			(default*)>
<!ATTLIST param			name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT bean			EMPTY>
<!ATTLIST bean			classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT file			EMPTY>
<!ATTLIST file		    name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT incookie		(default?)>
<!ATTLIST incookie		name CDATA #REQUIRED>

<!ELEMENT outcookie		(default?)>
<!ATTLIST outcookie		name CDATA #REQUIRED>

<!ELEMENT pathinfo		EMPTY>
<!ATTLIST pathinfo		mapping CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/extending_in_site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: extending_in_site.xml 3958 2008-05-26 12:04:14Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<element implementation="com.uwyn.rife.engine.testelements.extending.Blueprint">
		<property name="property1">value1</property>
		<property name="property2">value2</property>

		<input name="switch"/>

		<input name="input1"/>
		<input name="input2">
			<default>inputdefault</default>
		</input>

		<incookie name="incookie1"/>
		<incookie name="incookie2">
			<default>incookiedefault</default>
		</incookie>

		<submission name="submission1">
			<param name="param1"/>
			<param name="param2">
				<default>paramdefault</default>
			</param>
		</submission>

		<outcookie name="outcookie1"/>
		<outcookie name="outcookie2">
			<default>outcookiedefault</default>
		</outcookie>

		<exit name="exit1"/>
		<exit name="exit2"/>

		<output name="output1"/>
		<output name="output2">
			<default>outputdefault</default>
		</output>
	</element>

	<!-- EXTENDING SIMPLE -->
	<element id="SIMPLE" extends="Blueprint" url="/extending/simple">
		<flowlink srcexit="exit1" destid="SIMPLE"/>
		<datalink srcoutput="output1" destid="SIMPLE" destinput="input1"/>
		<flowlink srcexit="exit2" destid="SIMPLE"/>
		<datalink srcoutput="output2" destid="SIMPLE" destinput="input2"/>
	</element>

	<!-- EXTENDING CLASS OVERRIDING -->
	<element id="CLASSOVERRIDING" extends="Blueprint" implementation="com.uwyn.rife.engine.testelements.extending.ClassOverriding" url="/extending/classoverriding">
		<flowlink srcexit="exit1" destid="CLASSOVERRIDING"/>
		<datalink srcoutput="output1" destid="CLASSOVERRIDING" destinput="input1"/>
		<flowlink srcexit="exit2" destid="CLASSOVERRIDING"/>
		<datalink srcoutput="output2" destid="CLASSOVERRIDING" destinput="input2"/>
	</element>

	<!-- EXTENDING PROPERTIES OVERRIDING -->
	<element id="PROPERTIESOVERRIDING" extends="Blueprint" url="/extending/propertiesoverriding">
		<property name="property1">overriddenvalue1</property>
		<property name="property2">overriddenvalue2</property>
	</element>

	<!-- EXTENDING ADDING ELEMENTS -->
	<element id="ADDING" extends="Blueprint" implementation="com.uwyn.rife.engine.testelements.extending.Adding" url="/extending/adding">

		<property name="property3">value3</property>
		<property name="property4">value4</property>

		<input name="input3"/>
		<input name="input4">
			<default>inputdefault</default>
		</input>

		<incookie name="incookie3"/>
		<incookie name="incookie4">
			<default>incookiedefault</default>
		</incookie>

		<submission name="submission2">
			<param name="param1"/>
			<param name="param2">
				<default>submission2paramdefault</default>
			</param>
		</submission>

		<outcookie name="outcookie3"/>
		<outcookie name="outcookie4">
			<default>outcookiedefault</default>
		</outcookie>

		<exit name="exit3"/>
		<exit name="exit4"/>

		<output name="output3"/>
		<output name="output4">
			<default>outputdefault</default>
		</output>

		<flowlink srcexit="exit1" destid="ADDING"/>
		<datalink srcoutput="output1" destid="ADDING" destinput="input1"/>
		<flowlink srcexit="exit2" destid="ADDING"/>
		<datalink srcoutput="output2" destid="ADDING" destinput="input2"/>
		<flowlink srcexit="exit3" destid="ADDING"/>
		<datalink srcoutput="output3" destid="ADDING" destinput="input3"/>
		<flowlink srcexit="exit4" destid="ADDING"/>
		<datalink srcoutput="output4" destid="ADDING" destinput="input4"/>
	</element>

	<!-- EXTENDING MULTIPLE LEVELS -->
	<element id="MULTIPLELEVELS1" extends="Blueprint">

		<property name="property3">value3</property>
		<property name="property4">value4</property>

		<input name="input3"/>
		<input name="input4">
			<default>inputdefault</default>
		</input>

		<incookie name="incookie3"/>
		<incookie name="incookie4">
			<default>incookiedefault</default>
		</incookie>

	</element>

	<element id="MULTIPLELEVELS2" extends=".MULTIPLELEVELS1" implementation="com.uwyn.rife.engine.testelements.extending.MultipleLevels">

		<submission name="submission2">
			<param name="param1"/>
			<param name="param2">
				<default>submission2paramdefault</default>
			</param>
		</submission>

		<outcookie name="outcookie3"/>
		<outcookie name="outcookie4">
			<default>outcookiedefault</default>
		</outcookie>

	</element>

	<element id="MULTIPLELEVELS" extends="^.MULTIPLELEVELS2" url="/extending/multiplelevels">
		<exit name="exit3"/>
		<exit name="exit4"/>

		<output name="output3"/>
		<output name="output4">
			<default>outputdefault</default>
		</output>

		<flowlink srcexit="exit1" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output1" destid="MULTIPLELEVELS" destinput="input1"/>
		<flowlink srcexit="exit2" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output2" destid="MULTIPLELEVELS" destinput="input2"/>
		<flowlink srcexit="exit3" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output3" destid="MULTIPLELEVELS" destinput="input3"/>
		<flowlink srcexit="exit4" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output4" destid="MULTIPLELEVELS" destinput="input4"/>
	</element>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/cmf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: cmf.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalexit name="serve" destid="SERVE"/>
	
	<element id="SERVE" file="rife/cmf/serve_content.xml" url="/serve/*">
		<property name="datasource"><datasource><config param="unittestsdatasource"/></datasource></property>
	</element>

	<element id="SERVE_REPOSITORY" file="rife/cmf/serve_content.xml" url="/serve_repository/*">
		<property name="datasource"><datasource><config param="unittestsdatasource"/></datasource></property>
		<property name="repository">nondefault</property>
	</element>

	<element id="SERVE_NO_DATASOURCE" file="rife/cmf/serve_content.xml" url="/serve_nodatasource/*">
	</element>

	<element id="SERVE_EMBEDDED_IMAGE" file="rife/template/print.xml" url="/serve_embedded_image">
		<property name="name">cmf_serve_embedded_image</property>
	</element>

	<element id="SERVE_EMBEDDED_XHTML" file="rife/template/print.xml" url="/serve_embedded_xhtml">
		<property name="name">cmf_serve_embedded_xhtml</property>
	</element>

	<element file="element/cmf/content_querymanager_contentforhtml.xml" url="/contentforhtml">
		<property name="datasource"><config param="unittestsdatasource"/></property>
	</element>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/subsites.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: subsites.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalvar name="globalvar1">
		<default>default value1</default>
	</globalvar>
	<globalvar name="globalvar2">
		<default>default value2</default>
	</globalvar>
	<globalvar name="globalvar3"/>
	<globalvar name="globalvar4">
		<default>default value4</default>
	</globalvar>
	
	<globalexit name="globalexit1" destid="GLOBALDEST1"/>
	<globalexit name="globalexit2" destid="GLOBALDEST2" reflect="false"/>
	<globalexit name="globalexitarrival" destid="ARRIVAL_SUBSITE"/>
	
	<element id="GLOBALDEST1" file="element/subsites/globaldest1.xml" url="/subsites/globaldest1"/>
	<element id="GLOBALDEST2" file="element/subsites/globaldest2.xml" url="/subsites/globaldest2"/>
	
	<element id="SUBSITEPARENT1" file="element/subsites/parent1.xml"/>
	<element id="SUBSITEPARENT2" file="element/subsites/parent2.xml"/>
	
	<!-- absolute exit destination id -->
	<element id="ABSOLUTE_SOURCE" file="element/subsites/absolute_source.xml" url="/absolute">
		<flowlink srcexit="exit1" destid=".GLOBALEXIT_STRAIGHT^GLOBALVAR_STRAIGHT.ABSOLUTE_TARGET"/>
	</element>
	
	<!-- global exits -->
	<element id="GLOBALEXIT_ARRIVAL" file="element/subsites/globalexit/arrival.xml" url="/globalexit/arrival"/>
	<subsite id="GLOBALEXIT_ISOLATION" file="site/subsite/globalexit/isolation.xml" urlprefix="/globalexit/isolation" inherits="SUBSITEPARENT1"/>
	<subsite id="GLOBALEXIT_OVERLOADING" file="site/subsite/globalexit/overloading.xml" urlprefix="/globalexit/overloading" inherits="SUBSITEPARENT2"/>
	<subsite id="GLOBALEXIT_STRAIGHT" file="site/subsite/globalexit/straight.xml" urlprefix="/globalexit/straight"/>

	<!-- global vars -->
	<subsite id="GLOBALVAR_OVERRIDDEN" file="site/subsite/globalvar/overridden.xml" urlprefix="/globalvar/overridden" inherits="SUBSITEPARENT1"/>
	<subsite id="GLOBALVAR_DEFAULTTRIGGEREDCHILD" file="site/subsite/globalvar/defaulttriggeredchild.xml" urlprefix="/globalvar/defaulttriggeredchild" inherits="SUBSITEPARENT2"/>
	<subsite id="GLOBALVAR_STRAIGHT" file="site/subsite/globalvar/straight.xml" urlprefix="/globalvar/straight"/>
	
	<!-- inheritance -->
	<globalvar name="globalvar_inheritance1"/>
	<globalvar name="globalvar_inheritance2"/>
	<globalvar name="globalvar_inheritance3">
		<default>default value</default>
	</globalvar>
	
	<subsite id="INHERITANCE" file="site/subsite/inheritance.xml" urlprefix="/inheritance" inherits="SUBSITEPARENT1"/>
	
	<!-- arrival -->
	<arrival destid="ARRIVAL_SOURCE"/>

	<element id="ARRIVAL_SOURCE" file="element/subsites/arrivaltest_source.xml" url="/arrival_target_subsite">
		<flowlink srcexit="exit1" destid="ARRIVAL_TARGET_SUBSITE"/>
		<datalink srcoutput="output1" destid="ARRIVAL_TARGET_SUBSITE" destinput="input1"/>
		<datalink srcoutput="output2" destid="ARRIVAL_TARGET_SUBSITE" destinput="input2"/>
	</element>
	<subsite id="ARRIVAL_TARGET_SUBSITE" file="site/subsite/arrival.xml" urlprefix="/subsite/arrival"/>

	<element id="ARRIVALTEST_NOURL" file="element/subsites/arrivaltest_source.xml" url="/arrival_nourl">
		<flowlink srcexit="exit1" destid="ARRIVAL_NOURL"/>
		<datalink srcoutput="output1" destid="ARRIVAL_NOURL" destinput="input1"/>
		<datalink srcoutput="output2" destid="ARRIVAL_NOURL" destinput="input2"/>
	</element>
	<subsite id="ARRIVAL_NOURL" file="site/subsite/arrival_nourl.xml" urlprefix="/subsite/arrival_nourl"/>
	
	<element id="ARRIVAL_INHERITANCE_SOURCE" file="element/subsites/arrivaltest_source.xml" url="/arrival_inheritance">
		<flowlink srcexit="exit1" destid="ARRIVAL_INHERITANCE"/>
		<datalink srcoutput="output1" destid="ARRIVAL_INHERITANCE" destinput="input1"/>
		<datalink srcoutput="output2" destid="ARRIVAL_INHERITANCE" destinput="input2"/>
	</element>
	<subsite id="ARRIVAL_INHERITANCE" file="site/subsite/arrival.xml" urlprefix="/subsite/arrival_inheritance" inherits="SUBSITEPARENT1"/>

	<subsite id="ARRIVAL_SUBSITE" file="site/subsite/arrival_subsite.xml" urlprefix="/subsite/arrival_subsite"/>
	
	<subsite id="ARRIVAL_SUBSITE_TRAILING_SLASH" file="site/subsite/arrival_subsite.xml" urlprefix="/subsite/arrival_subsite_slash/"/>
	
	<element id="ARRIVAL_REDIRECT" file="element/subsites/arrivaltest_source.xml" url="/arrival_redirect">
		<flowlink srcexit="exit1" destid="ARRIVAL_TARGET_REDIRECT"/>
		<datalink srcoutput="output1" destid="ARRIVAL_TARGET_REDIRECT" destinput="input1"/>
		<datalink srcoutput="output2" destid="ARRIVAL_TARGET_REDIRECT" destinput="input2"/>
	</element>
	<subsite id="ARRIVAL_TARGET_REDIRECT" file="site/subsite/arrival_redirect.xml" urlprefix="/subsite/arrival_redirect"/>
	
	<element id="ARRIVAL_REDIRECT_NOURL" file="element/subsites/arrivaltest_source.xml" url="/arrival_redirect_nourl">
		<flowlink srcexit="exit1" destid="ARRIVAL_TARGET_REDIRECT_NOURL"/>
		<datalink srcoutput="output1" destid="ARRIVAL_TARGET_REDIRECT_NOURL" destinput="input1"/>
		<datalink srcoutput="output2" destid="ARRIVAL_TARGET_REDIRECT_NOURL" destinput="input2"/>
	</element>
	<subsite id="ARRIVAL_TARGET_REDIRECT_NOURL" file="site/subsite/arrival_redirect_nourl.xml" urlprefix="/subsite/arrival_redirect_nourl"/>
	
	<subsite id="ARRIVAL_DEFAULT_TEMPLATE" file="site/subsite/arrival_default_template.xml" urlprefix="/subsite/arrival_default_template"/>

	<!-- departure -->
	<subsite id="DEPARTURE" file="site/subsite/departure.xml" urlprefix="/departure"/>

	<!-- url oddities -->
	<subsite id="MULTIPLE_SLASH" file="site/subsite/multiple_slash.xml" urlprefix="/subsite/multiple_slash///"/>
	
	<!-- nofile -->
	<subsite id="NOFILE" urlprefix="nofile">
		<element id="SIMPLE" implementation="com.uwyn.rife.engine.testelements.engine.Simple" url="simple"/>
	</subsite>
	
	<!-- annotations -->
	<element implementation="com.uwyn.rife.engine.testelements.subsites.AnnotationsSource"/>
	<subsite id="ANNOTATIONS">
		<element implementation="com.uwyn.rife.engine.testelements.subsites.AnnotationsDest"/>
	</subsite>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/roleuser_janino.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: roleuser_janino.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalvar name="authid"/>

	<element id="MEMORY_ROLE_ADMIN" file="element/authentication/memory_authenticated_role.xml"/>
	<element id="MEMORY_ROLE_ADMIN_TARGET" file="element/roleuser/target_janino.xml" url="/memory/role_admin" inherits="MEMORY_ROLE_ADMIN"/>

	<element id="MEMORY_ROLE_MAINT" file="element/authentication/memory_authenticated_role2.xml"/>
	<element id="MEMORY_ROLE_MAINT_TARGET" file="element/roleuser/target_janino.xml" url="/memory/role_maint" inherits="MEMORY_ROLE_MAINT"/>
	
	<element id="IDENTIFIED" file="element/roleuser/identified.xml">
		<property name="authElementId">MEMORY_ROLE_ADMIN</property>
	</element>
	<element id="IDENTIFIED_TARGET" file="element/roleuser/target_janino.xml" url="/identified" inherits="IDENTIFIED"/>

	<element file="element/roleuser/explicit_evaluation_janino.xml" url="/explicit_evaluation" inherits="MEMORY_ROLE_ADMIN"/>

	<element id="DATABASE_ROLE_ADMIN" file="element/authentication/database_authenticated_role.xml"/>
	<element id="DATABASE_ROLE_ADMIN_TARGET" file="element/roleuser/target_janino.xml" url="/database/role_admin" inherits="DATABASE_ROLE_ADMIN"/>
	
	<element id="DATABASE_ROLE_MAINT" file="element/authentication/database_authenticated_role2.xml"/>
	<element id="DATABASE_ROLE_MAINT_TARGET" file="element/roleuser/target_janino.xml" url="/database/role_maint" inherits="DATABASE_ROLE_MAINT"/>
	
	<element id="DATABASE_ENCRYPTED" file="element/authentication/database_authenticated_encrypted.xml"/>
	<element id="DATABASE_ENCRYPTED_TARGET" file="element/roleuser/target_janino.xml" url="/database/encrypted" inherits="DATABASE_ENCRYPTED"/>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/dwr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: dwr.xml 3927 2008-04-21 10:22:16Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<element id="Hello" file="rife/template/print.xml" url="hello">
		<property name="name">dwr_hello</property>
	</element>
	<element id="DwrHello" file="rife/ajax/dwr.xml" url="dwr/hello/*">
		<property name="xmlConfiguratorPath">dwr/hello.xml</property>
		<property name="allowGetForSafariButMakeForgeryEasier">true</property>
		<property name="allowScriptTagRemoting">true</property>
		<property name="debug">false</property>
	</element>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/statesession.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: statesession.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<state store="session">
		<!-- SUBMISSIONS -->
		<element id="INPUTSPRESERVED" file="element/submission/inputspreserved.xml" url="/submissions/inputspreserved"/>
		<element id="FILEUPLOAD_SIMPLE" file="element/submission/fileupload.xml" url="/fileupload/simple"/>
	
		<!-- EXITS DIRECT LINK -->
		<state store="query">
			<element id="DIRECTLINK_SOURCE" file="element/exits/directlink_source.xml" url="/exits/directlink/source">
				<flowlink srcexit="exit1" destid="DIRECTLINK_DESTINATION"/>
				<datalink srcoutput="output1" destid="DIRECTLINK_DESTINATION" destinput="input1"/>
				<datalink srcoutput="output2" destid="DIRECTLINK_DESTINATION" destinput="input2"/>
			</element>
		</state>
		<element id="DIRECTLINK_DESTINATION" file="element/exits/directlink_destination.xml" url="/exits/directlink/destination"/>
	
		<!-- EXITS GENERATED URL -->
		<state store="query">
			<element id="GENERATEDURL_SOURCE" file="element/exits/generatedurl_source.xml" url="/exits/generatedurl/source">
				<flowlink srcexit="exit1" destid="GENERATEDURL_DESTINATION1"/>
				<flowlink srcexit="exit2" destid="GENERATEDURL_DESTINATION2"/>
				<datalink srcoutput="output1" destid="GENERATEDURL_DESTINATION1" destinput="input1"/>
				<datalink srcoutput="output2" destid="GENERATEDURL_DESTINATION1" destinput="input2"/>
				<datalink srcoutput="output2" destid="GENERATEDURL_DESTINATION2" destinput="input1"/>
				<datalink srcoutput="output3" destid="GENERATEDURL_DESTINATION2" destinput="input2"/>
			</element>
		</state>
		<element id="GENERATEDURL_DESTINATION1" file="element/exits/generatedurl_destination1.xml" url="/exits/generatedurl/destination1"/>
		<element id="GENERATEDURL_DESTINATION2" file="element/exits/generatedurl_destination2.xml" url="/exits/generatedurl/destination2"/>
	
		<!-- EXITS DIRECT LINK QUERYSTATE-->
		<element id="DIRECTLINK_SOURCE_QUERYSTATE" file="element/exits/directlink_source.xml" url="/exits/directlink/source/querystate">
			<flowlink srcexit="exit1" destid="DIRECTLINK_DESTINATION_QUERYSTATE"/>
			<datalink srcoutput="output1" destid="DIRECTLINK_DESTINATION_QUERYSTATE" destinput="input1"/>
			<datalink srcoutput="output2" destid="DIRECTLINK_DESTINATION_QUERYSTATE" destinput="input2"/>
		</element>
		<state store="query">
			<element id="DIRECTLINK_DESTINATION_QUERYSTATE" file="element/exits/directlink_destination.xml" url="/exits/directlink/destination/querystate"/>
		</state>
		
		<!-- SUBSITE -->
		<subsite id="SUBSITE" file="site/subsite/statesession.xml" urlprefix="/subsite"/>
		
	</state>
</site>

=== gbevin/rife/rife_v1_remaining/src/examples/tutorial/03_numberguess/src/sites/numberguess.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: numberguess.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
    <arrival destid="Start"/>
    
    <element id="Start" url="/start"
    		 implementation="tutorial.numberguess.Start">
    		 
		<input name="gameid"/>
		<output name="gameid"/>
		
		<exit name="started"/>
	
        <flowlink srcexit="started" destid="Guess">
			<datalink srcoutput="gameid" destinput="gameid"/>
		</flowlink>
    </element>
    
    <element id="Success"
    		 implementation="tutorial.numberguess.Success">
    		 
		<input name="gameid"/>
		<exit name="start"/>
		
        <flowlink srcexit="start" destid="Guess"/>
    </element>
    
    <element id="Guess" url="/guess"
    		 implementation="tutorial.numberguess.Guess">
    		 
		<input name="gameid"/>
		<submission name="performGuess">
			<param name="guess">
				<default>-1</default>
			</param>
		</submission>
		<output name="gameid"/>
		
		<exit name="start"/>
		<exit name="success"/>

        <flowlink srcexit="start" destid="Start">
			<datalink srcoutput="gameid" destinput="gameid"/>
		</flowlink>

        <flowlink srcexit="success" destid="Success">
			<datalink srcoutput="gameid" destinput="gameid"/>
		</flowlink>
    </element>
</site>
