=== gbevin/rife/rife_v1_remaining/shared/dtd/site.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: site.dtd 3930 2008-04-24 11:10:22Z gbevin $
  -  PUBLIC ID: -//Rifers.org//RIFE Site 1.6.2//EN
  -  SYSTEM ID: http://rifers.org/dtd/site_1_6_2.dtd
  -->

<!ELEMENT site			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST site	    	fallbackid CDATA #IMPLIED>

<!ELEMENT group			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | errorhandler)*>
<!ATTLIST group			inherits CDATA #IMPLIED
						pre CDATA #IMPLIED>

<!ELEMENT state			(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST state			store CDATA #IMPLIED> <!-- by default the "query" and "session" state stores are supported -->

<!ELEMENT globalvar		(default*)>
<!ATTLIST globalvar	    name CDATA #REQUIRED>

<!ELEMENT globalcookie	(default*)>
<!ATTLIST globalcookie	name CDATA #REQUIRED>

<!ELEMENT globalbean	EMPTY>
<!ATTLIST globalbean	classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT globalexit	EMPTY>
<!ATTLIST globalexit    name CDATA #REQUIRED
						destid CDATA #IMPLIED
						reflect (0|f|false|1|t|true) "false"
						snapback (0|f|false|1|t|true) "false"
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT arrival		EMPTY>
<!ATTLIST arrival    	destid CDATA #REQUIRED
						redirect (0|f|false|1|t|true) "false">

<!ELEMENT departure		EMPTY>
<!ATTLIST departure    	srcid CDATA #REQUIRED>

<!ELEMENT errorhandler	(type*)>
<!ATTLIST errorhandler	destid CDATA #REQUIRED>

<!ELEMENT type			EMPTY>
<!ATTLIST type	    	classname CDATA #REQUIRED>

<!ELEMENT subsite		(globalvar | globalcookie | globalbean | globalexit | element | group | subsite | state | arrival | departure | property | errorhandler)*>
<!ATTLIST subsite		id ID #REQUIRED
						file CDATA #IMPLIED
						urlprefix CDATA #IMPLIED
						inherits CDATA #IMPLIED
						pre CDATA #IMPLIED>

<!ELEMENT default		(#PCDATA | config)*>

<!ELEMENT config	    EMPTY>
<!ATTLIST config	    param CDATA #REQUIRED>

<!ELEMENT element		(property | datalink | flowlink | autolink | exit | childtrigger | input | inbean | output | outbean | submission | incookie | outcookie | pathinfo)*>
<!ATTLIST element		file CDATA #IMPLIED
						id ID #IMPLIED
						url CDATA #IMPLIED
						inherits CDATA #IMPLIED
						pre CDATA #IMPLIED
						implementation CDATA #IMPLIED
                        extends CDATA #IMPLIED
                        contenttype CDATA #IMPLIED
                        pathinfo (loose|strict) #IMPLIED>

<!ELEMENT property		(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST property		name CDATA #REQUIRED>

<!ELEMENT participant	(#PCDATA | config | participant | datasource | template)*>
<!ATTLIST participant	name CDATA #REQUIRED>

<!ELEMENT datasource	(#PCDATA | config | participant)*>

<!ELEMENT template		(#PCDATA | config | participant)*>
<!ATTLIST template		type CDATA #IMPLIED>

<!ELEMENT datalink		EMPTY>
<!ATTLIST datalink		srcoutput CDATA #IMPLIED
						srcoutbean CDATA #IMPLIED
						destid CDATA #IMPLIED
						snapback (0|f|false|1|t|true) "false"
						destinput CDATA #IMPLIED
						destinbean CDATA #IMPLIED>

<!ELEMENT flowlink		(datalink)*>
<!ATTLIST flowlink		srcexit CDATA #REQUIRED
						destid CDATA #IMPLIED
						snapback (0|f|false|1|t|true) "false"
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT autolink		(datalink)*>
<!ATTLIST autolink		srcexit CDATA #REQUIRED
						destid CDATA #IMPLIED
						redirect (0|f|false|1|t|true) "false"
						inheritance (preserve|cancel) "preserve"
						embedding (preserve|cancel) "preserve"
						continuations (preserve|cancel) "preserve">

<!ELEMENT exit			EMPTY>
<!ATTLIST exit			name CDATA #REQUIRED>

<!ELEMENT childtrigger	EMPTY>
<!ATTLIST childtrigger	name CDATA #REQUIRED>

<!ELEMENT input			(default*)>
<!ATTLIST input			name CDATA #REQUIRED>

<!ELEMENT inbean		EMPTY>
<!ATTLIST inbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT output		(default*)>
<!ATTLIST output		name CDATA #REQUIRED>

<!ELEMENT outbean		EMPTY>
<!ATTLIST outbean		classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT submission	(param | bean | file)*>
<!ATTLIST submission	name CDATA #REQUIRED
						scope (local|global) "local"
						continuations (preserve|cancel) "preserve">

<!ELEMENT param			(default*)>
<!ATTLIST param			name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT bean			EMPTY>
<!ATTLIST bean			classname CDATA #REQUIRED
						prefix CDATA #IMPLIED
						name CDATA #IMPLIED
						group CDATA #IMPLIED>

<!ELEMENT file			EMPTY>
<!ATTLIST file		    name CDATA #IMPLIED
						regexp CDATA #IMPLIED>

<!ELEMENT incookie		(default?)>
<!ATTLIST incookie		name CDATA #REQUIRED>

<!ELEMENT outcookie		(default?)>
<!ATTLIST outcookie		name CDATA #REQUIRED>

<!ELEMENT pathinfo		EMPTY>
<!ATTLIST pathinfo		mapping CDATA #REQUIRED>

=== gbevin/rife/rife_v1_remaining/src/examples/tutorial/07_authentication/src/sites/authentication.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: authentication.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalcookie name="authid"/>

	<globalexit name="admin" destid="Admin"/>
	
	<arrival destid="Home"/>

	<!-- embeddable login box -->
    <element id="AuthBox" file="authentication/box.xml"/>
    
    <element id="Logout" file="rife/logout/passthrough/memory.xml">
    	<flowlink srcexit="logged_out" snapback="true"/>
    </element>
    
    <element id="LoginBox" file="credentials.xml" inherits="AuthBox">
    	<flowlink srcexit="logout" destid="Logout"/>
    </element>

	<!-- visitor section -->
    <element id="Home" extends="rife/template/print.xml" url="/home">
		<property name="name">home</property>
		<exit name="more"/>
		
    	<flowlink srcexit="more" destid="More"/>
    </element>
    
    <element id="More" extends="rife/template/print.xml" url="/more">
		<property name="name">more</property>
		<exit name="home"/>
		
    	<flowlink srcexit="home" destid="Home"/>
    </element>

	<!-- administration section -->
    <element id="AuthAdmin" file="authentication/administration.xml"/>
    
    <element id="Admin" extends="rife/template/print.xml" url="/admin" inherits="AuthAdmin">
		<property name="name">administration</property>
		<exit name="home"/>
		
    	<flowlink srcexit="home" destid="Home"/>
    </element>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/extending.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: extending.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<!-- EXTENDING SIMPLE -->
	<element id="SIMPLE" file="element/extending/simple.xml" url="/extending/simple">
		<flowlink srcexit="exit1" destid="SIMPLE"/>
		<datalink srcoutput="output1" destid="SIMPLE" destinput="input1"/>
		<flowlink srcexit="exit2" destid="SIMPLE"/>
		<datalink srcoutput="output2" destid="SIMPLE" destinput="input2"/>
	</element>
	
	<!-- EXTENDING CLASS OVERRIDING -->
	<element id="CLASSOVERRIDING" file="element/extending/classoverriding.xml" url="/extending/classoverriding">
		<flowlink srcexit="exit1" destid="CLASSOVERRIDING"/>
		<datalink srcoutput="output1" destid="CLASSOVERRIDING" destinput="input1"/>
		<flowlink srcexit="exit2" destid="CLASSOVERRIDING"/>
		<datalink srcoutput="output2" destid="CLASSOVERRIDING" destinput="input2"/>
	</element>
	
	<!-- EXTENDING STATICPROPERTIES OVERRIDING -->
	<element id="STATICPROPERTIESOVERRIDING" file="element/extending/staticpropertiesoverriding.xml" url="/extending/staticpropertiesoverriding"/>
	
	<!-- EXTENDING ADDING ELEMENTS -->
	<element id="ADDING" file="element/extending/adding.xml" url="/extending/adding">
		<flowlink srcexit="exit1" destid="ADDING"/>
		<datalink srcoutput="output1" destid="ADDING" destinput="input1"/>
		<flowlink srcexit="exit2" destid="ADDING"/>
		<datalink srcoutput="output2" destid="ADDING" destinput="input2"/>
		<flowlink srcexit="exit3" destid="ADDING"/>
		<datalink srcoutput="output3" destid="ADDING" destinput="input3"/>
		<flowlink srcexit="exit4" destid="ADDING"/>
		<datalink srcoutput="output4" destid="ADDING" destinput="input4"/>
	</element>
	
	<!-- EXTENDING MULTIPLE LEVELS -->
	<element id="MULTIPLELEVELS" file="element/extending/multiplelevels3.xml" url="/extending/multiplelevels">
		<flowlink srcexit="exit1" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output1" destid="MULTIPLELEVELS" destinput="input1"/>
		<flowlink srcexit="exit2" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output2" destid="MULTIPLELEVELS" destinput="input2"/>
		<flowlink srcexit="exit3" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output3" destid="MULTIPLELEVELS" destinput="input3"/>
		<flowlink srcexit="exit4" destid="MULTIPLELEVELS"/>
		<datalink srcoutput="output4" destid="MULTIPLELEVELS" destinput="input4"/>
	</element>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/globals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: globals.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<globalvar name="globalvar1"/>
	<globalvar name="globalvar2"/>
	<globalexit name="globalexit1" destid="DESTINATION3" reflect="0"/>
	<globalexit name="globalexit2" reflect="true"/>
	
	<globalexit name="globalexit6" destid="."/>
	
	<globalcookie name="cookie1"/>
	
	<arrival destid="INPUTSSOURCE"/>
	
	<!-- BASIC GLOBALS WITH EXITS -->
	<element id="SOURCE" url="/globals/source" file="element/globals/source.xml">
		<flowlink srcexit="exit1" destid="DESTINATION1"/>
		<flowlink srcexit="exit2" destid="DESTINATION2"/>
	</element>
	<element id="DESTINATION1" url="/globals/destination1" file="element/globals/destination1.xml"/>
	<element id="DESTINATION2" url="/globals/destination2" file="element/globals/destination2.xml"/>
	<element id="DESTINATION3" url="/globals/destination3" file="element/globals/destination3.xml"/>
	
	<!-- BASIC GLOBALS WITH INJECTION -->
	<element id="INJECTION" url="/globals/injection" file="element/globals/source.xml">
		<flowlink srcexit="exit1" destid="INJECTIONDEST1"/>
		<flowlink srcexit="exit2" destid="INJECTIONDEST2"/>
	</element>
	<element id="INJECTIONDEST1" url="/globals/injectiondest1" file="element/globals/injectiondest1.xml"/>
	<element id="INJECTIONDEST2" url="/globals/injectiondest2" file="element/globals/injectiondest2.xml"/>
	
	<!-- GROUP -->
	<group>
		<globalvar name="globalvar3"/>
		<globalvar name="globalvar4"/>
		<globalexit name="globalexit3" destid="GROUP_DESTINATION3" reflect="f"/>
		<globalexit name="globalexit4" reflect="t"/>
		
		<element id="GROUP_SOURCE" url="/globals/group/source" file="element/globals/group/source.xml">
			<flowlink srcexit="exit1" destid="GROUP_DESTINATION1"/>
			<flowlink srcexit="exit2" destid="GROUP_DESTINATION2"/>
		</element>
		<element id="GROUP_DESTINATION1" url="/globals/group/destination1" file="element/globals/group/destination1.xml"/>
		<element id="GROUP_DESTINATION2" url="/globals/group/destination2" file="element/globals/group/destination2.xml"/>
		<element id="GROUP_DESTINATION3" url="/globals/group/destination3" file="element/globals/group/destination3.xml"/>
	</group>

	<!-- GROUP ISOLATION -->
	<group>
		<globalvar name="globalvar5"/>
		
		<element id="GROUP_ISOLATION_SOURCE" url="/globals/group/isolation_source" file="element/globals/group/isolation_source.xml">
			<flowlink srcexit="exit1" destid="GROUP_ISOLATION_DESTINATION1"/>
			<flowlink srcexit="exit2" destid="GROUP_ISOLATION_DESTINATION2"/>
		</element>
		<element id="GROUP_ISOLATION_DESTINATION1" url="/globals/group/isolation_destination1" file="element/globals/group/isolation_destination.xml"/>
	</group>

	<group>
		<globalvar name="globalvar2">
			<default>default value 2 local</default>
		</globalvar>
		<globalvar name="globalvar5"/>
		
		<element id="GROUP_ISOLATION_DESTINATION2" url="/globals/group/isolation_destination2" file="element/globals/group/isolation_destination.xml"/>
	</group>


	<element id="SUBMISSION" url="/globals/submission" file="element/globals/submission.xml"/>

	<!-- INPUT OVERRIDING -->
	<element id="INPUTSSOURCE" url="/globalvars/inputs/source" file="element/globals/vars_inputs_source.xml">
		<flowlink srcexit="exit" destid="INPUTSDESTINATION"/>
		<datalink srcoutput="output1"  destid="INPUTSDESTINATION" destinput="input1"/>
		<datalink srcoutput="output2"  destid="INPUTSDESTINATION" destinput="input2"/>
	</element>
	<element id="INPUTSDESTINATION" url="/globalvars/inputs/destination" file="element/globals/vars_inputs_destination.xml"/>
	
	<!-- GLOBAL BEAN -->
	<group>
		<globalbean classname="com.uwyn.rife.engine.testelements.globals.BeanImpl"/>
		<globalexit name="exit" reflect="true"/>

		<element id="BEAN_NORMAL" url="/globals/bean/normal" file="element/globals/bean_normal.xml"/>
	</group>
	
	<!-- GLOBAL BEAN PREFIX -->
	<group>
		<globalbean classname="com.uwyn.rife.engine.testelements.globals.BeanImpl" prefix="prefix_"/>
		<globalexit name="exit" reflect="1"/>

		<element id="BEAN_PREFIX" url="/globals/bean/prefix" file="element/globals/bean_prefix.xml"/>
	</group>
	
	<!-- NAMED GLOBAL BEAN -->
	<group>
		<globalbean name="globalbean1" classname="com.uwyn.rife.engine.testelements.globals.BeanImpl"/>
		<globalexit name="exit" reflect="true"/>

		<element id="NAMED_BEAN_NORMAL" url="/globals/namedbean/normal" file="element/globals/namedbean_normal.xml"/>
	</group>
	
	<!-- NAMED GLOBAL BEAN PREFIX -->
	<group>
		<globalbean name="globalbean2"  classname="com.uwyn.rife.engine.testelements.globals.BeanImpl" prefix="prefix_"/>
		<globalexit name="exit" reflect="1"/>

		<element id="NAMED_BEAN_PREFIX" url="/globals/namedbean/prefix" file="element/globals/namedbean_prefix.xml"/>
	</group>
	
	<!-- GLOBALEXIT SNAPBACK -->
	<group>
		<globalexit name="exit2" snapback="true"/>
		
		<element id="SNAPBACK_SOURCE" file="element/globals/snapback_source.xml" url="/globals/snapback/source">
			<flowlink srcexit="exit1" destid="SNAPBACK_PASSTHROUGH"/>
		</element>
		<element id="SNAPBACK_PASSTHROUGH" file="element/globals/snapback_passthrough.xml" url="/globals/snapback/passthrough"/>
	</group>
	
	<!--GLOBAL COOKIES-->
	<group>
		<globalcookie name="cookie2"/>
		<globalcookie name="cookie3"/>
		
		<element id="GLOBALCOOKIE_VALID_SOURCE" file="element/globals/globalcookie_source.xml" url="/globals/globalcookie/valid/source"/>
		<element id="GLOBALCOOKIE_VALID_DESTINATION" file="element/globals/globalcookie_destination.xml" url="/globals/globalcookie/valid/destination"/>
	</group>
	<group>
		<globalcookie name="cookie2"/>
	
		<element id="GLOBALCOOKIE_INVALID_SOURCE" file="element/globals/globalcookie_source.xml" url="/globals/globalcookie/invalid/source"/>
		<element id="GLOBALCOOKIE_INVALID_SOURCE2" file="element/globals/globalcookie_source2.xml" url="/globals/globalcookie/invalid/source2"/>
	</group>
	<group>
		<globalcookie name="defcookie1">
			<default>the first cookie</default>
		</globalcookie>
		
		<globalcookie name="defcookie2"/>
		
		<globalcookie name="defcookie3">
			<default><config param="ENGINE_ELEMENT_CONFIG_VALUE"/></default>
		</globalcookie>
		
		<globalcookie name="defcookie4">
			<default><config param="ENGINE_ELEMENT_CONFIG_VALUE"/></default>
		</globalcookie>
		<globalcookie name="defcookie5">
			<default>the fifth cookie</default>
		</globalcookie>
		
		<element id="GLOBALCOOKIE_DEFAULTS" file="element/globals/globalcookie_defaults.xml" url="/globals/globalcookie/defaults"/>
	</group>
	
	<!-- GLOBAL EXIT TO ROOT ARRIVAL -->
	<element id="GLOBALEXIT_TO_ROOT_ARRIVAL" file="element/globals/globalexit_to_root_arrival.xml" url="/globals/globalexit_to_root_arrival">
		<datalink srcoutput="output1"  destid="." destinput="input1"/>
		<datalink srcoutput="output2"  destid="." destinput="input2"/>
	</element>
</site>

=== gbevin/rife/rife_v1_remaining/programs/unittests/config/site/exits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  -  Copyright 2001-2008 Geert Bevin <gbevin[remove] at uwyn dot com>
  -  Licensed under the Apache License, Version 2.0 (the "License")
  -  $Id: exits.xml 3918 2008-04-14 17:35:35Z gbevin $
  -->

<!DOCTYPE site SYSTEM "/dtd/site.dtd">

<site>
	<!-- EXITS SIMPLE -->
	<element id="SIMPLE_SOURCE" file="element/exits/simple_source.xml" url="/exits/simple/source">
		<flowlink srcexit="exit1" destid="SIMPLE_DESTINATION"/>
	</element>
	<element id="SIMPLE_DESTINATION" file="element/exits/simple_destination.xml" url="/exits/simple/destination"/>

	<!-- EXITS SELECTIVE -->
	<element id="SELECTIVE_SOURCE" file="element/exits/selective_source.xml" url="/exits/selective/source">
		<flowlink srcexit="exit1" destid="SELECTIVE_DESTINATION1"/>
		<flowlink srcexit="exit2" destid="SELECTIVE_DESTINATION2"/>
		<flowlink srcexit="exit3" destid="SELECTIVE_DESTINATION3"/>
	</element>
	<element id="SELECTIVE_DESTINATION1" file="element/exits/selective_destination1.xml" url="/exits/selective/destination1"/>
	<element id="SELECTIVE_DESTINATION2" file="element/exits/selective_destination2.xml" url="/exits/selective/destination2"/>
	<element id="SELECTIVE_DESTINATION3" file="element/exits/selective_destination3.xml" url="/exits/selective/destination3"/>

	<!-- EXITS DIRECT LINK -->
	<element id="DIRECTLINK_SOURCE" file="element/exits/directlink_source.xml" url="/exits/directlink/source">
		<flowlink srcexit="exit1" destid="DIRECTLINK_DESTINATION"/>
		<datalink srcoutput="output1" destid="DIRECTLINK_DESTINATION" destinput="input1"/>
		<datalink srcoutput="output2" destid="DIRECTLINK_DESTINATION" destinput="input2"/>
	</element>
	<element id="DIRECTLINK_DESTINATION" file="element/exits/directlink_destination.xml" url="/exits/directlink/destination"/>

	<!-- EXITS FLOWLINK SPECIFIC DATALINKS -->
	<element id="FLOWLINKSPECIFIC_SOURCE" file="element/exits/flowlinkspecific_source.xml" url="/exits/flowlinkspecific/source">
		<datalink srcoutput="output3" destid="FLOWLINKSPECIFIC_DESTINATION" destinput="input2"/>
		<flowlink srcexit="exit1" destid="FLOWLINKSPECIFIC_DESTINATION">
			<datalink srcoutput="output1" destinput="input1"/>
		</flowlink>
		<flowlink srcexit="exit2" destid="FLOWLINKSPECIFIC_DESTINATION">
			<datalink srcoutput="output2" destinput="input1"/>
		</flowlink>
	</element>
	<element id="FLOWLINKSPECIFIC_DESTINATION" file="element/exits/flowlinkspecific_destination.xml" url="/exits/flowlinkspecific/destination"/>
	
	<!-- EXITS AUTOLINK -->
	<element id="AUTOLINK_SOURCE" implementation="com.uwyn.rife.engine.testelements.exits.AutolinkSource" url="/exits/autolink/source">
		<input name="type"/>
		<output name="value1"/>
		<output name="value2"/>
		<output name="value3"/>
		<outbean name="bean1" classname="com.uwyn.rife.engine.testelements.exits.BeanImpl1"/>
		<outbean name="bean2" classname="com.uwyn.rife.engine.testelements.exits.BeanImpl2" prefix="out_"/>
		<autolink srcexit="AUTOLINK_DESTINATION"/>
	</element>
	<element id="AUTOLINK_DESTINATION" implementation="com.uwyn.rife.engine.testelements.exits.AutolinkDestination" url="/exits/autolink/destination">
		<input name="value1"/>
		<input name="value2"/>
		<input name="value4"/>
		<inbean name="bean1" classname="com.uwyn.rife.engine.testelements.exits.BeanImpl1"/>
		<inbean name="bean3" classname="com.uwyn.rife.engine.testelements.exits.BeanImpl2" prefix="in_"/>
	</element>
	
	<!-- EXITS ANNOTATIONS AUTOLINK -->
	<element implementation="com.uwyn.rife.engine.testelements.exits.AutolinkAnnotationSource"/>
	<element implementation="com.uwyn.rife.engine.testelements.exits.AutolinkAnnotationDestination"/>
	
	<!-- EXITS GENERATED URL -->
	<element id="GENERATEDURL_SOURCE" file="element/exits/generatedurl_source.xml" url="/exits/generatedurl/source">
		<flowlink srcexit="exit1" destid="GENERATEDURL_DESTINATION1"/>
		<flowlink srcexit="exit2" destid="GENERATEDURL_DESTINATION2"/>
		<datalink srcoutput="output1" destid="GENERATEDURL_DESTINATION1" destinput="input1"/>
		<datalink srcoutput="output2" destid="GENERATEDURL_DESTINATION1" destinput="input2"/>
		<datalink srcoutput="output2" destid="GENERATEDURL_DESTINATION2" destinput="input1"/>
		<datalink srcoutput="output3" destid="GENERATEDURL_DESTINATION2" destinput="input2"/>
	</element>
	<element id="GENERATEDURL_DESTINATION1" file="element/exits/generatedurl_destination1.xml" url="/exits/generatedurl/destination1"/>
	<element id="GENERATEDURL_DESTINATION2" file="element/exits/generatedurl_destination2.xml" url="/exits/generatedurl/destination2"/>

	<!-- EXITS GENERATED URL OVERFLOW -->
	<element id="GENERATEDURLOVERFLOW_SOURCE" file="element/exits/generatedurloverflow_source.xml" url="/exits/generatedurloverflow/source">
		<flowlink srcexit="exit1" destid="GENERATEDURLOVERFLOW_DESTINATION"/>
		<datalink srcoutput="output1" destid="GENERATEDURLOVERFLOW_DESTINATION" destinput="input1"/>
		<datalink srcoutput="output2" destid="GENERATEDURLOVERFLOW_DESTINATION" destinput="input2"/>
	</element>
	<element id="GENERATEDURLOVERFLOW_DESTINATION" file="element/exits/generatedurloverflow_destination.xml" url="/exits/generatedurloverflow/destination"/>

	<!-- EXITS GENERATED FORM -->
	<element id="GENERATEDFORM_SOURCE" file="element/exits/generatedform_source.xml" url="/exits/generatedform/source">
		<flowlink srcexit="exit1" destid="GENERATEDFORM_DESTINATION1"/>
		<flowlink srcexit="exit2" destid="GENERATEDFORM_DESTINATION2"/>
		<datalink srcoutput="output1" destid="GENERATEDFORM_DESTINATION1" destinput="input1"/>
		<datalink srcoutput="output2" destid="GENERATEDFORM_DESTINATION1" destinput="input2"/>
		<datalink srcoutput="output2" destid="GENERATEDFORM_DESTINATION2" destinput="input1"/>
		<datalink srcoutput="output3" destid="GENERATEDFORM_DESTINATION2" destinput="input2"/>
	</element>
	<element id="GENERATEDFORM_DESTINATION1" file="element/exits/generatedform_destination1.xml" url="/exits/generatedform/destination1"/>
	<element id="GENERATEDFORM_DESTINATION2" file="element/exits/generatedform_destination2.xml" url="/exits/generatedform/destination2"/>
	
	<!-- EXITS SNAPBACK SIMPLE -->
	<element id="SNAPBACK_SIMPLE_SOURCE" file="element/exits/snapback_simple_source.xml" url="/exits/snapback/simple">
		<flowlink srcexit="exit1" destid="SNAPBACK_SIMPLE_PASSTHROUGH"/>
	</element>
	<element id="SNAPBACK_SIMPLE_PASSTHROUGH" file="element/exits/snapback_simple_passthrough.xml">
		<flowlink srcexit="exit2" snapback="true"/>
	</element>
	
	<!-- EXITS SNAPBACK DATALINK -->
	<element id="SNAPBACK_DATALINK_SOURCE" file="element/exits/snapback_datalinks_source.xml" url="/exits/snapback/datalinks">
		<flowlink srcexit="exit1" destid="SNAPBACK_DATALINK_PASSTHROUGH"/>
		<datalink srcoutput="param1" destid="SNAPBACK_DATALINK_PASSTHROUGH" destinput="param1"/>
	</element>
	<element id="SNAPBACK_DATALINK_PASSTHROUGH" file="element/exits/snapback_datalinks_passthrough.xml">
		<flowlink srcexit="exit2" snapback="true"/>
		<datalink srcoutput="output1" snapback="true" destinput="input1"/>
		<datalink srcoutput="output2" snapback="true" destinput="input2"/>
		<datalink srcoutput="output3" snapback="true" destinput="input3"/>
	</element>

	<!-- EXITS BEAN NORMAL -->
	<element id="BEAN_NORMAL_SOURCE" file="element/exits/bean_normal_source.xml" url="/exits/bean/normal">
		<flowlink srcexit="beanexit" destid="BEAN_NORMAL_DESTINATION"/>
		<datalink srcoutbean="outbean1" destid="BEAN_NORMAL_DESTINATION" destinbean="inbean1"/>
	</element>
	<element id="BEAN_NORMAL_DESTINATION" file="element/exits/bean_normal_destination.xml"/>

	<!-- EXITS BEAN DIFFERENT -->
	<element id="BEAN_DIFFERENT_SOURCE" file="element/exits/bean_normal_source.xml" url="/exits/bean/different">
		<flowlink srcexit="beanexit" destid="BEAN_DIFFERENT_DESTINATION"/>
		<datalink srcoutbean="outbean1" destid="BEAN_DIFFERENT_DESTINATION" destinbean="inbean2"/>
	</element>
	<element id="BEAN_DIFFERENT_DESTINATION" file="element/exits/bean_normal_destination.xml"/>

	<!-- EXITS BEAN SNAPBACK -->
	<element id="BEAN_SNAPBACK" file="element/exits/bean_snapback.xml" url="/exits/bean/snapback">
		<flowlink srcexit="beanexit" snapback="1"/>
		<datalink srcoutbean="outbean1" snapback="1" destinbean="inbean1"/>
	</element>

	<!-- EXITS BEAN PREFIX SAME-->
	<element id="BEAN_PREFIX_SAME_SOURCE" file="element/exits/bean_prefix_source.xml" url="/exits/bean/prefix/same">
		<flowlink srcexit="beanexit" destid="BEAN_PREFIX_SAME_DESTINATION"/>
		<datalink srcoutbean="outbean1" destid="BEAN_PREFIX_SAME_DESTINATION" destinbean="inbean1"/>
	</element>
	<element id="BEAN_PREFIX_SAME_DESTINATION" file="element/exits/bean_prefix_destination.xml"/>

	<!-- EXITS BEAN PREFIX DIFFERENT-->
	<element id="BEAN_PREFIX_DIFFERENT_SOURCE" file="element/exits/bean_prefix_source.xml" url="/exits/bean/prefix/different">
		<flowlink srcexit="beanexit" destid="BEAN_PREFIX_DIFFERENT_DESTINATION"/>
		<datalink srcoutbean="outbean1" destid="BEAN_PREFIX_DIFFERENT_DESTINATION" destinbean="inbean2"/>
	</element>
	<element id="BEAN_PREFIX_DIFFERENT_DESTINATION" file="element/exits/bean_prefix_destination.xml"/>

	<!-- EXIT REDIRECT -->
	<element id="REDIRECT_SOURCE" file="element/exits/redirect_source.xml" url="/exits/redirect/source">
		<flowlink srcexit="exit_intern" destid="REDIRECT_DESTINATION"/>
		<flowlink srcexit="exit_redirect" destid="REDIRECT_DESTINATION" redirect="1"/>
		<datalink srcoutput="output1" destid="REDIRECT_DESTINATION" destinput="input1"/>
		<datalink srcoutput="output2" destid="REDIRECT_DESTINATION" destinput="input2"/>
	</element>
	<element id="REDIRECT_DESTINATION" file="element/exits/redirect_destination.xml" url="/exits/redirect/destination"/>
</site>
